### ISSUE TITLE
Error in fanc auto - .hic as input

### ISSUE THREAD

**Issue by Rseq** [vaquerizaslab/fanc#10]
Hi,

This thread was mentioned here https://github.com/vaquerizaslab/fanc/issues/9#issuecomment-586955698
When using juice .hic as input in fanc auto, I get the following error:

```
$ fanc auto '/media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic' '/media/test/Data/Data/HiC/HiC_fused_150_PE/FANC'
2020-02-17 12:46:45,532 INFO Output folder: /media/test/Data/Data/HiC/HiC_fused_150_PE/FANC/
2020-02-17 12:46:45,532 INFO Input files: /media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic
2020-02-17 12:46:45,532 INFO Input file types: hic
2020-02-17 12:46:45,533 INFO Final basename: K5testEtOH.allValidPairs (you can change this with the -n option!)
2020-02-17 12:46:45,533 INFO Creating output folders...
/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py:273: UserWarning: No resolution chosen for Juicer Hic! Using 2500000bp
  warnings.warn("No resolution chosen for Juicer Hic! Using {}bp".format(resolution))
usage: fanc hic [-h] [-b BIN_SIZE] [-l FILTER_LOW_COVERAGE]
                [-r FILTER_LOW_COVERAGE_RELATIVE] [-a] [-d FILTER_DIAGONAL]
                [--marginals-plot MARGINALS_PLOT] [--reset-filters]
                [--downsample DOWNSAMPLE] [-i] [-k] [-w] [-c] [--only-inter]
                [-s STATS] [--statistics-plot STATS_PLOT]
                [--chromosomes CHROMOSOMES [CHROMOSOMES ...]] [-f]
                [-t THREADS] [-tmp]
                input [input ...]
fanc hic: error: File (/media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic) type <class 'fanc.compatibility.juicer.JuicerHic'> not supported.Provide Pairs or Hic files!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 1338, in hic
    "Provide Pairs or Hic files!".format(original_input_file, type(o)))
  File "/usr/lib/python3.6/argparse.py", line 2402, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.6/argparse.py", line 2389, in exit
    _sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 1341, in hic
    o.close()
AttributeError: 'JuicerHic' object has no attribute 'close'
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 114, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/auto.py", line 1186, in auto
    runner.run()
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/auto.py", line 141, in run
    "Cancelling execution of all tasks.".format(task.id))
RuntimeError: Task 3b2018a4-1a22-4505-a546-282b36d7f25d had non-zero exit status. Cancelling execution of all tasks.

```

thanks,

**Comment by kaukrise** [comment]
Hi again, and thanks. There is a lot of output here due to the parallelisation, but the relevant line is this one: 

```
fanc hic: error: File (/media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic) type <class 'fanc.compatibility.juicer.JuicerHic'> not supported.Provide Pairs or Hic files!
```

This is because there should be no need to convert your Juicer .hic file to FAN-C format, because is is already compatible. Can you try simply plotting a region from your juicer matrix using `fancplot`? From your previous issue I'm assuming this is a human sample, so you could try this, please?

```
fancplot 1:15mb-25mb -p square /media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic
```

This should show your matrix directly.

**Comment by Rseq** [comment]
Hi,

Thanks for your prompt reply. It is human indeed and it did work.
However, I thought that was not compatible due to the following issue:

```
$ fanc compartments -w /media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic /media/test/Data/Data/HiC/HiC_fused_150_PE/K5testEtOH.ab
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 3785, in compartments
    matrix = fanc.load(input_file, tmpdir=tmp)
  File "/usr/local/lib/python3.6/dist-packages/fanc/tools/load.py", line 85, in load
    return JuicerHic(file_name, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'tmpdir'
```

So.. it is not related then, isn't?

**Comment by kaukrise** [comment]
Thank you, you found a different bug there. The universal `load` function tried to pass an argument to the Juicer compatibility layer that it does not support. 

Instead of ignoring the argument, I thought it would be nice to support working from temporary files also in Juicer and Cooler files, so I have pushed a new version with this fix (`0.8.21`). I tested it on my local Juicer and Cooler files, but I would be grateful if you could also try it on the compartmentalisation command that you posted above.

**Comment by Rseq** [comment]
Hi, 

Many thanks for your reply.
I ran again the same command after updating to the new version and:

```
$ fanc compartments -w /media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/test_EtOH/K5_test_EtOH.allValidPairs.hic /media/test/Data/Data/HiC/HiC_fused_150_PE/K5_test_EtOH.ab
/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py:288: UserWarning: No resolution chosen for Juicer Hic! Using 2500000bp
  warnings.warn("No resolution chosen for Juicer Hic! Using {}bp".format(resolution))
2020-02-18 11:08:50,256 INFO Computing AB compartment matrix
/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py:574: RuntimeWarning: divide by zero encountered in true_divide
  return np.array(vectors[resolution]) / scaling_factors[resolution][chromosome_ix]
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 3807, in compartments
    per_chromosome=not whole_genome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/compartments.py", line 113, in from_hic
    m = hic.matrix(oe=True, oe_per_chromosome=oe_per_chromosome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 991, in matrix
    for source, sink, weight in matrix_entries:
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 948, in <genexpr>
    entry_iter = ((i, j,
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 920, in offset_iter
    for edge in edge_iter:
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 690, in __call__
    for edge in edge_iter:
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 925, in _edges_subset
    raise ValueError("Cannot subset rows across multiple chromosomes!")
ValueError: Cannot subset rows across multiple chromosomes!
Closing remaining open files:/media/test/Data//usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py:288: UserWarning: No resolution chosen for Juicer Hic! Using 2500000bp/HiC/HiC_fused_150_PE/K5_test_EtOH.ab...done

```
Should we close this thread here as the original report was sorted out and open a new one for this bug?

Also, how do I force to generate the AB compartments in a specific resolution? 
As it says here that I did not choose ` /usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py:288: UserWarning: No resolution chosen for Juicer Hic! Using 2500000bp` and it was not clear for me from the arguments list. 

Another topic is about the `-w, --whole-genome` argument. It is not clear to me what it does. Does it mean that without specifying this argument, the calculations to AB compartments will be for a specific chr or it will just not consider somehow trans interactions?

Many thanks again

**Comment by kaukrise** [comment]
Hi again,

first of all, regarding your bug: Juicer normalises matrices on a per-chromosome basis and, as the error suggests, does therefore not allow subsetting across multiple chromosomes. FAN-C does the same by default, but you can, in principle, also normalise the matrix as a whole (although this is not recommended because you may introduce artefacts based on chromosome size). Since you may have a use-case that warrants this (e.g. only looking at inter-chromosomal data, etc), FAN-C does not prevent you from subsetting across multiple chromosomes.

This is where the `-w` argument comes in. When you specify it, FAN-C will calculate the correlation matrix and eigenvectors on the whole genome matrix at once. As mentioned above, this is most likely *not* what you want, given the way the normalisation is done. In fact, it is not possible with Juicer files, as you saw above. Instead, remove `-w`, and FAN-C will calculate the AB matrix for each chromosome separately, using only intra-chromosomal data. Note that the result is still only one object (with all chromosomes in it), the only difference between using and not using `-w` is the way correlation values are calculated.

**Comment by kaukrise** [comment]
Oh, and you choose a resolution using `@` notation:

```
fanc auto /media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/testEtOH/K5testEtOH.allValidPairs.hic@1000000 /media/test/Data/Data/HiC/HiC_fused_150_PE/FANC
```

**Comment by Rseq** [comment]
Hi again,

I received another error message after removing the -w argument:

```
$ fanc compartments -e /media/test/Data/Data/HiC/HiC_fused_150_PE/K5_test_EtOH_AB_compartments.png /media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/test_EtOH/K5_test_EtOH.allValidPairs.hic@500000 /media/test/Data/Data/HiC/HiC_fused_150_PE/K5_test_EtOH.ab
2020-02-18 13:57:38,667 INFO Computing AB compartment matrix
AB 100% (25 of 25) |#################################################################################| Elapsed Time: 0:00:00 ETA:  00:00:00
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 3807, in compartments
    per_chromosome=not whole_genome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/compartments.py", line 91, in from_hic
    m = hic.matrix((chromosome, chromosome), oe=True, oe_per_chromosome=oe_per_chromosome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 987, in matrix
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 939, in regions_and_matrix_entries
    intra_expected, chromosome_intra_expected, inter_expected = self.expected_values(norm=norm)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 601, in expected_values
    intra_expected[chromosome] = self.expected_value_vector(chromosome, self._normalisation)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 574, in expected_value_vector
    return np.array(vectors[resolution]) / scaling_factors[resolution][chromosome_ix]
KeyError: 24
Closing remaining open files:/media/test/Data/Data/HiC/HiC_fused_150_PE/K5_test_EtOH.ab...done
```

Any ideas of what is going on?

Thanks again

**Comment by kaukrise** [comment]
Hmm, I cannot reproduce this error using my test Juicer files. Can you run the following code and send me the output, please?

```
python -c 'import fanc; hic = fanc.load("/media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/test_EtOH/K5_test_EtOH.allValidPairs.hic@500000"); print(hic.chromosomes()); vectors, sf = hic.expected_value_vectors(); print(sf[500000])'
```

**Comment by Rseq** [comment]
Here is:

```
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M']
{1: 0.8769552464937732, 2: 0.9778344836554894, 3: 0.9457206228930173, 4: 1.236647964407402, 5: 1.0143440075273937, 6: 1.0876140066760331, 7: 0.8784687053579056, 8: 0.8965571106740134, 9: 1.4004478717627529, 10: 0.9409853145272994, 11: 0.929410187083797, 12: 0.8484962161234252, 13: 1.972638975631551, 14: 1.1559656793581037, 15: 1.1491955335733803, 16: 0.9022246733407777, 17: 0.4959187859896916, 18: 1.0147959174574541, 19: 0.7402340228298465, 20: 0.7908355918994138, 21: 1.3439298501365347, 22: 1.3026434730201673, 23: 1.0268099059511702, 24: 697.6790610059169, 25: 0.0}
```

**Comment by kaukrise** [comment]
Thank you, and maybe please this one?

```
python -c 'import fanc; hic = fanc.load("/media/test/Data/Data/HiC/HiC_fused_150_PE/Juicer/test_EtOH/K5_test_EtOH.allValidPairs.hic@500000"); print(hic.chromosomes()); vectors, sf = hic.normalised_expected_value_vectors(hic._normalisation); print(sf[500000]); print(hic.resolutions()); print(hic._normalisation); print(hic._resolution)'
```

**Comment by Rseq** [comment]
Sure:

```
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'M']
{1: 0.8912833873717958, 2: 0.9947420106815782, 3: 0.964247648068679, 4: 1.256755627141968, 5: 1.0340805384765634, 6: 1.1033584020276848, 7: 0.8972787992429606, 8: 0.9160493374319737, 9: 1.4468748260327327, 10: 0.9605951195337291, 11: 0.9494945490476988, 12: 0.8672996977200621, 13: 2.0136679046535084, 14: 1.1791769755060442, 15: 1.1733707997929228, 16: 0.9156836302177861, 17: 0.49473406434777145, 18: 1.0349720427575047, 19: 0.7535805728352455, 20: 0.8031195218259096, 21: 1.3521373638950134, 22: 1.3200764011436577, 23: 1.0463390797228618, 25: 0.0}
([2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000], [])
KR
500000
```

**Comment by kaukrise** [comment]
Thanks a lot! Juicer internally uses scaling factors on the expected values of each chromosome, which differ for each normalisation type. For some reason, the "KR" normalisation is missing the scaling factor for chromosome Y in your matrix. You can see that it is the only one missing (even MT has one, although it is 0), and I don't know if that is intentional or a Juicer bug.
I think the safest way of handling this is to add an exception, which explicitly sets the scaling factor to 0 if it is not found in the file. The alternative would be to set it to 1., but I have to assume it is missing for a reason.

**Comment by kaukrise** [comment]
The latest version should fix the issue you are seeing (`0.8.22`). It is available via Pypi

**Comment by Rseq** [comment]
It is working now. Many thanks!
It could be the fact that is a cell line without Y (XX only).

**Comment by kaukrise** [comment]
Thank you for your help, and please let me know if you run into any more issues!
