### ISSUE TITLE
Aggregate error

### ISSUE THREAD

**Issue by cpadillla1331** [vaquerizaslab/fanc#101]
I get this error when trying to use aggregate for loops. I followed the loop calling workflow to get the bedpe file
When I run this command:
 fanc aggregate micro.800M.hic@10kb fanc.test.bedpe fanc.agg -p fanc.agg.png --loops

I get this error
2022-03-16 20:24:17,698 INFO FAN-C version: 0.9.23
2022-03-16 20:24:18,605 INFO Detected BEDPE. Running pairwise region extraction
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 127, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.8/dist-packages/fanc/commands/fanc_commands.py", line 4743, in aggregate
    aggregate_matrix = AggregateMatrix.from_center_pairs(matrix, region_pairs,
  File "/usr/local/lib/python3.8/dist-packages/fanc/architecture/aggregate.py", line 418, in from_center_pairs
    for (r1, r2), m in _loop_matrix_iterator(hic, pair_regions, pixels=pixels,
  File "/usr/local/lib/python3.8/dist-packages/fanc/architecture/aggregate.py", line 736, in _loop_matrix_iterator
    r1 = list(hic.regions(a1))[0].copy()
  File "/usr/local/lib/python3.8/dist-packages/fanc/compatibility/juicer.py", line 889, in _region_subset
    for i, start in enumerate(range(subset_start, min(cl, region.end), self._resolution)):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by kaukrise** [comment]
Hi,

this error indicates that one of `subset_start`, `cl` (chromosome length), `region.end`, or `self._resolution` (matrix resolution) is not an integer, as one would expect.

To check which one is the culprit, can you please run the same command with the following version?

[fanc-0.9.23b2.tar.gz](https://github.com/vaquerizaslab/fanc/files/8282518/fanc-0.9.23b2.tar.gz)

It contains a catch block in the problematic code and will output the variable values right before the error. Once I know where exactly the problem is, I can start fixing it!

Thanks!

**Comment by DittmanC** [comment]
I have used the updated version, but still got the error as below.
My bedpe looks like this format as an example
chr5	153950000	153975000	chr5	153950000	153975000	+
chr5	153975000	154350000	chr5	153975000	154350000	-
...

./fanc aggregate x.hic x.bedpe test.agg
2022-06-21 22:48:56,798 INFO FAN-C version: 0.9.24
/disk3/users/dittman/miniconda3/lib/python3.9/site-packages/fanc/compatibility/juicer.py:330: UserWarning: No resolution chosen for Juicer Hic - using 2500000bp. Specify a custom resolution using <.hic file>@<resolution>
  warnings.warn("No resolution chosen for Juicer Hic - using {}bp. "
2022-06-21 22:48:56,838 INFO Detected BEDPE. Running pairwise region extraction
Traceback (most recent call last):
  File "/./fanc/bin/./fanc", line 127, in <module>
    Fanc()
  File "/./fanc/bin/./fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/./lib/python3.9/site-packages/fanc/commands/fanc_commands.py", line 4790, in aggregate
    aggregate_matrix = AggregateMatrix.from_center_pairs(matrix, region_pairs,
  File "/./site-packages/fanc/architecture/aggregate.py", line 418, in from_center_pairs
    for (r1, r2), m in _loop_matrix_iterator(hic, pair_regions, pixels=pixels,
  File "/./python3.9/site-packages/fanc/architecture/aggregate.py", line 736, in _loop_matrix_iterator
    r1 = list(hic.regions(a1))[0].copy()
  File "/./lib/python3.9/site-packages/fanc/compatibility/juicer.py", line 901, in _region_subset
    for i, start in enumerate(range(subset_start, min(cl, region.end), self._resolution)):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by kaukrise** [comment]
I think I have identified the issue - could someone please test their own files with this version?

[fanc-0.9.25b1.tar.gz](https://github.com/vaquerizaslab/fanc/files/8974184/fanc-0.9.25b1.tar.gz)

```
pip install fanc-0.9.25b1.tar.gz
```

Thank you
