### ISSUE TITLE
fanc pairs (HDF5ExtError: Problems creating the table)

### ISSUE THREAD

**Issue by saraebell** [vaquerizaslab/fanc#105]
I am running **fanc pairs** with sorted .sam files. It looks like the job runs for a while before crashing with the following **HDF5 ExtError** (shown below). I have moved as much out of the working directory to free up space so I do not believe it is a memory/space issue, additionally I allocated 236GB of total memory on a GPU node. Any help is appreciated, thank you for your time. 

2022-03-21 17:47:02,642 INFO FAN-C version: 0.9.22
2022-03-21 17:47:02,646 INFO Getting genome regions (fragments or bins)
2022-03-21 17:47:02,646 INFO Getting regions
2022-03-21 17:47:03,333 INFO Three arguments detected, assuming SAM/BAM input.
2022-03-21 17:47:03,416 INFO Using filters appropriate for Bowtie2.
Buffers   0% (0 of 969) |                | Elapsed Time: 0:00:00 ETA:  --:--:--
Buffers   0% (1 of 969) |                | Elapsed Time: 0:00:00 ETA:  00:00:00
Buffers   1% (10 of 969) |               | Elapsed Time: 0:00:00 ETA:   0:00:12
Buffers   2% (20 of 969) |               | Elapsed Time: 0:00:00 ETA:   0:00:12
Buffers   3% (30 of 969) |               | Elapsed Time: 0:00:00 ETA:   0:00:09
Buffers   4% (39 of 969) |               | Elapsed Time: 0:00:00 ETA:   0:00:09
Buffers   5% (49 of 969) |               | Elapsed Time: 0:00:00 ETA:   0:00:08
Buffers   6% (59 of 969) |               | Elapsed Time: 0:00:00 ETA:   0:00:08
Buffers   7% (68 of 969) |#              | Elapsed Time: 0:00:00 ETA:   0:00:07
Buffers   8% (78 of 969) |#              | Elapsed Time: 0:00:00 ETA:   0:00:07
Buffers   9% (88 of 969) |#              | Elapsed Time: 0:00:00 ETA:   0:00:07
Buffers  10% (97 of 969) |#              | Elapsed Time: 0:00:00 ETA:   0:00:07
Buffers  11% (107 of 969) |#             | Elapsed Time: 0:00:00 ETA:   0:00:06
Buffers  12% (117 of 969) |#             | Elapsed Time: 0:00:00 ETA:   0:00:06
Buffers  13% (126 of 969) |#             | Elapsed Time: 0:00:00 ETA:   0:00:06
Buffers  14% (136 of 969) |#             | Elapsed Time: 0:00:00 ETA:   0:00:05
Buffers  15% (146 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:05
Buffers  16% (156 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:05
Buffers  17% (165 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:05
Buffers  18% (175 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:05
Buffers  19% (185 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:05
Buffers  20% (194 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  21% (204 of 969) |##            | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  22% (214 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  23% (223 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  24% (233 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  25% (243 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  26% (252 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  27% (262 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  28% (272 of 969) |###           | Elapsed Time: 0:00:01 ETA:   0:00:04
Buffers  29% (282 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Buffers  30% (291 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Buffers  31% (301 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Buffers  32% (311 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Buffers  33% (320 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Buffers  34% (330 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Buffers  35% (340 of 969) |####          | Elapsed Time: 0:00:01 ETA:   0:00:03
Traceback (most recent call last):
  File "/home/014843907/anaconda3/envs/SDs/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/014843907/anaconda3/envs/SDs/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 970, in pairs
    pairs = generate_pairs(sam1_file, sam2_file, regions,
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/pairs.py", line 125, in generate_pairs_split
    pairs.add_read_pairs_from_sam(sam1_file, sam2_file, threads=threads, batch_size=batch_size,
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/pairs.py", line 1478, in add_read_pairs_from_sam
    self.flush()
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/pairs.py", line 1242, in flush
    RegionPairsTable.flush(self, silent=silent)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/matrix.py", line 1706, in flush
    self._flush_edges(silent=silent, update_mappability=update_mappability)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/matrix.py", line 1685, in _flush_edges
    self._edge_buffer.flush()
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/matrix.py", line 1436, in flush
    edge_table = self._matrix._edge_table(partition[0], partition[1], create_index=False)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/matrix.py", line 1641, in _edge_table
    edge_table = MaskedTable(self._edges,
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/general.py", line 663, in __init__
    t.Table.__init__(self, parentnode, name,
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/tables/table.py", line 807, in __init__
    super().__init__(parentnode, name, new, filters, byteorder, _log,
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/tables/leaf.py", line 259, in __init__
    super().__init__(parentnode, name, _log)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/tables/node.py", line 249, in __init__
    self._v_objectid = self._g_create()
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/tables/table.py", line 995, in _g_create
    self._v_objectid = self._create_table(
  File "tables/tableextension.pyx", line 209, in tables.tableextension.Table._create_table
tables.exceptions.HDF5ExtError: Problems creating the table
Closing remaining open files:pairs_out/dm3/s2/2291.pairs...done
/var/spool/slurmd/job49221/slurm_script: line 15: 163882 Segmentation fault      fanc pairs sort_out/dm3/s2/2291_1_sort.sam sort_out/dm3/s2/2291_2_sort.sam pairs_out/dm3/s2/2291.pairs --genome refrags_out/dm3_refrags/dm3_HindIII_rf.bed --filter-unmappable --filter-multimapping-strict --filter-quality 30 --threads 4
2022-03-21 18:02:08,186 INFO FAN-C version: 0.9.22
2022-03-21 18:02:08,189 INFO One argument received, assuming existing Pairs object.

**Comment by saraebell** [comment]
Issue seems to be re-occurring, any suggestions would be appreciated. Thank you.

**Comment by saraebell** [comment]
Additional HDF5 errors. 

2022-04-18 20:33:46,841 INFO FAN-C version: 0.9.22
2022-04-18 20:33:46,845 INFO Getting genome regions (fragments or bins)
2022-04-18 20:33:46,845 INFO Getting regions
2022-04-18 20:33:47,451 INFO Three arguments detected, assuming SAM/BAM input.
2022-04-18 20:33:47,558 INFO Using filters appropriate for Bowtie2.
Traceback (most recent call last):
  File "/home/014843907/anaconda3/envs/SDs/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/014843907/anaconda3/envs/SDs/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 970, in pairs
    pairs = generate_pairs(sam1_file, sam2_file, regions,
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/pairs.py", line 120, in generate_pairs_split
    pairs._add_region(region, preserve_attributes=False)
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/fanc/regions.py", line 611, in _add_region
    row.append()
  File "tables/tableextension.pyx", line 1339, in tables.tableextension.Row.append
  File "tables/tableextension.pyx", line 1343, in tables.tableextension.Row._flush_buffered_rows
  File "/home/014843907/anaconda3/envs/SDs/lib/python3.8/site-packages/tables/table.py", line 2130, in _save_buffered_rows
    self._append_records(lenrows)
  File "tables/tableextension.pyx", line 495, in tables.tableextension.Table._append_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 291, in H5Dwrite
    can't write data
  File "H5VLcallback.c", line 2113, in H5VL_dataset_write
    dataset write failed
  File "H5VLcallback.c", line 2080, in H5VL__dataset_write
    dataset write failed
  File "H5VLnative_dataset.c", line 207, in H5VL__native_dataset_write
    can't write data
  File "H5Dio.c", line 762, in H5D__write
    can't write data
  File "H5Dchunk.c", line 2683, in H5D__chunk_write
    unable to read raw data chunk
  File "H5Dchunk.c", line 3982, in H5D__chunk_lock
    unable to preempt chunk(s) from cache
  File "H5Dchunk.c", line 3648, in H5D__chunk_cache_prune
    unable to preempt one or more raw data cache entry
  File "H5Dchunk.c", line 3497, in H5D__chunk_cache_evict
    cannot flush indexed storage buffer
  File "H5Dchunk.c", line 3417, in H5D__chunk_flush_entry
    unable to write raw data to file
  File "H5Fio.c", line 191, in H5F_shared_block_write
    write through page buffer failed
  File "H5PB.c", line 1021, in H5PB_write
    write through metadata accumulator failed
  File "H5Faccum.c", line 831, in H5F__accum_write
    file write failed
  File "H5FDint.c", line 240, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 864, in H5FD__sec2_write
    file write failed: time = Mon Apr 18 20:34:08 2022
, filename = 'pairs_out/z11/3575.pairs', file descriptor = 3, errno = 5, error message = 'Input/output error', buf = 0x55b0a5642308, total write size = 262080, bytes this sub-write = 262080, bytes actually written = 18446744073709551615, offset = 0

End of HDF5 error back trace

Problems appending the records.
Closing remaining open files:pairs_out/z11/3575.pairs...done
/var/spool/slurmd/job50550/slurm_script: line 15: 164287 Segmentation fault      fanc pairs sort_out/z11/3575_1_sort.sam sort_out/z11/3575_2_sort.sam pairs_out/z11/3575.pairs --genome refrags_out/danRer11_refrags/danRer_MboI_rf.bed --filter-unmappable --filter-multimapping-strict --filter-quality 30 --threads 4
slurmstepd: error: *** JOB 50550 ON g15 CANCELLED AT 2022-04-18T20:35:46 ***

**Comment by saraebell** [comment]
resolved this issue by making more space available in working directory.
