### ISSUE TITLE
Issue with coordinates from .bw files when using fancplot with --window-size option

### ISSUE THREAD

**Issue by MariaRig** [vaquerizaslab/fanc#110]
Hey! I'm having an issue with fancplot, when using the --window-size option. 
I can make a plot with several tracks and matrices like this:
```
fancplot $reg \
    -o fancplots/`date +%Y-%m`\_plot_top$position\_new_boundary.png \
    -p triangular -vmin 0 -vmax 0.035 $hic_matrices_path/all_merged_neg_10kb.hic --title "DOX-" \
    -p triangular -vmin 0 -vmax 0.035 $hic_matrices_path/all_merged_pos_10kb.hic --title "DOX+" \
    -p triangular $hic_matrices_path/foldchange_ref_query_all_merged.hic -s 0 -c coolwarm --title foldchange_ref_query \
    -p layer consensus_gained_TAD_boundaries_only_regions_with_negative_insulation_in_DUX4.bed --title "New TAD boundary" \
    -p line $scRNA_path/10X_10_CTRL.unique.bw  --title "scRNA_DOX-" \
    -p line $scRNA_path/10X_12_8CLC.unique.bw  --title "scRNA_DOX+" \
    -p gene $hg38_gencode
```
But when I add `--window-size 1000000`  like this: `fancplot $reg --window-size 1mb -o ...` then it doesn't work unless I remove  the bigwig files. I've tried with different bigwigs and the issue is repeated. It seems to have an issue with interpreting the modified coordinates, but only for the bw files.
The error I get is the following:

```
/home/mrigaud/.local/bin/fancplot:161: UserWarning: There was an error with plot 0, region chr6:41100000-41190000 (Traceback (most recent call last):
  File "/home/mrigaud/.local/bin/fancplot", line 144, in __init__
    fig, axes = gf.plot(plot_region)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/base_plotter.py", line 292, in plot
    plot_output = self._plot(region)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 1091, in _plot
    for i, (x, w, h, c) in enumerate(self._bar_values(region)):
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 1076, in _bar_values
    for region in region_iter:
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 934, in _region_iter
    for region in data.regions(region, **kwargs):
  File "/home/mrigaud/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 1674, in _region_subset
    for start, end, score in self.region_intervals(r):
  File "/home/mrigaud/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 955, in region_intervals
    raw_intervals = self._region_intervals(region, score_field=score_field, *args, **kwargs)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 1686, in _region_intervals
    intervals = self.bw.intervals(region.chromosome, region.start, region.end)
RuntimeError: The start coordinate must be a number!
)
  warnings.warn("There was an error with plot {}, region {}:{}-{} ({})".format(i, region.chromosome,
2022-05-10 16:35:55,606 WARNING The start coordinate must be a number!
```
Thank you!

**Comment by kaukrise** [comment]
Hey Maria,

thanks for reporting this - can you please install the following beta version:

[fanc-0.9.23b3.tar.gz](https://github.com/vaquerizaslab/fanc/files/8677071/fanc-0.9.23b3.tar.gz)

Then please run the command in debug mode (`fancplot -vvv`) and look for a line that contains `Invalid interval bounds?` and paste that here.

**Comment by MariaRig** [comment]
Hi Kai,
This is what I get: 
```
2022-05-13 16:55:38,478 DEBUG Invalid interval bounds? chr11:124315000-125315000
/home/mrigaud/.local/bin/fancplot:186: UserWarning: There was an error with plot 0, region chr11:124770000-124860000 (Traceback (most recent call last):
  File "/home/mrigaud/.local/bin/fancplot", line 169, in __init__
    fig, axes = gf.plot(plot_region)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/base_plotter.py", line 292, in plot
    plot_output = self._plot(region)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 993, in _plot
    for i, x, y in self._line_values(region):
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 987, in _line_values
    x, y = self.values_from_region_iter(region_iter, self.attribute)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/base_plotter.py", line 523, in values_from_region_iter
    return self._STYLES[self.style](self, regions, attribute)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/base_plotter.py", line 510, in _get_values_per_mid
    for region in regions:
  File "/home/mrigaud/.local/lib/python3.8/site-packages/fanc/plotting/plotter.py", line 934, in _region_iter
    for region in data.regions(region, **kwargs):
  File "/home/mrigaud/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 1674, in _region_subset
    for start, end, score in self.region_intervals(r):
  File "/home/mrigaud/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 955, in region_intervals
    raw_intervals = self._region_intervals(region, score_field=score_field, *args, **kwargs)
  File "/home/mrigaud/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 1686, in _region_intervals
    intervals = self.bw.intervals(region.chromosome, region.start, region.end)
RuntimeError: The start coordinate must be a number!
)
  warnings.warn("There was an error with plot {}, region {}:{}-{} ({})".format(i, region.chromosome,
2022-05-13 16:55:38,500 WARNING The start coordinate must be a number!
```
Thanks,
Maria

**Comment by kaukrise** [comment]
Thanks for sending the log! I am quite puzzled

```
DEBUG Invalid interval bounds? chr11:124315000-125315000
```

`124315000` looks like a number to me - perhaps it is in the wrong format. The BigWig file is probably not big - can you share it with me (perhaps on ownCloud), so I can try it out?

**Comment by kaukrise** [comment]
Also, just out of curiosity, what version of `genomic_regions` are you running?

```
# python
import genomic_regions
print(genomic_regions.__version__)
```

**Comment by MariaRig** [comment]
Hi Kai, I have put a couple of bw files in my shared folder: MR_shared/Projects/DUX4_project/bw_files_kai. You have the link in mattermost. 
Regarding genomic_regions, I'm running version 0.0.10

**Comment by kaukrise** [comment]
Sorry, I don't seem to have access to that folder. One file to reproduce the issue will be enough, you can also upload it in Mattermost

**Comment by MariaRig** [comment]
It's working now, thank you!!
