### ISSUE TITLE
fanc insulation -w 40kb error

### ISSUE THREAD

**Issue by Kuang1230** [vaquerizaslab/fanc#114]
Recently, we use your FAN-C to run the TAD analysis (insulation score). We want to set the window size as 40kb, but it not  succeed with fllowing information:
fanc insulation ../LW_180d_Fat_HiC_pre_juicebox_sorted.hic ../test/LW_fat_insulation -w 40kb -i  -o bed
2022-06-08 09:41:26,813 INFO FAN-C version: 0.9.24
/home/yxzhao/miniconda3/lib/python3.9/site-packages/fanc/compatibility/juicer.py:330: UserWarning: No resolution chosen for Juicer Hic - using 2500000bp. Specify a custom resolution using <.hic file>@<resolution>
  warnings.warn("No resolution chosen for Juicer Hic - using {}bp. "
2022-06-08 09:41:28,482 INFO Chosen window sizes: 40000
2022-06-08 09:41:30,972 INFO 1 (1/20)
Traceback (most recent call last):
  File "/home/yxzhao/miniconda3/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/yxzhao/miniconda3/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/yxzhao/miniconda3/lib/python3.9/site-packages/fanc/commands/fanc_commands.py", line 3792, in insulation
    _domain_scores(parser, input_file, output_file, output_format,
  File "/home/yxzhao/miniconda3/lib/python3.9/site-packages/fanc/commands/fanc_commands.py", line 3844, in _domain_scores
    scores = score_class.from_hic(matrix, file_name=output_file,
  File "/home/yxzhao/miniconda3/lib/python3.9/site-packages/fanc/architecture/domains.py", line 342, in from_hic
    values_by_chromosome[w_ix][k] /= bin_window_size ** 2
ZeroDivisionError: division by zero
Closing remaining open files:6SWZEJ...done

However, when we use the defaut -w the FANC can run, but the window size were not matched either .hic (-r 2500000,1000000,500000,250000,100000,50000,40000,25000,10000,5000) file or your paper descripted ( https://doi.org/10.1186/s13059-020-02215-9). The ouput information is as fllowing:

fanc insulation ../LW_180d_Fat_HiC_pre_juicebox_sorted.hic ../test/LW_fat_insulation  -i  -o bed
2022-06-08 09:46:16,246 INFO FAN-C version: 0.9.24
/home/yxzhao/miniconda3/lib/python3.9/site-packages/fanc/compatibility/juicer.py:330: UserWarning: No resolution chosen for Juicer Hic - using 2500000bp. Specify a custom resolution using <.hic file>@<resolution>
  warnings.warn("No resolution chosen for Juicer Hic - using {}bp. "
2022-06-08 09:46:16,303 INFO Chosen window sizes: 7500000 12500000 17500000 25000000 37500000
2022-06-08 09:46:18,502 INFO 1 (1/20)
2022-06-08 09:46:18,621 INFO 10 (2/20)
2022-06-08 09:46:18,705 INFO 11 (3/20)
2022-06-08 09:46:18,800 INFO 12 (4/20)
2022-06-08 09:46:18,872 INFO 13 (5/20)
2022-06-08 09:46:18,973 INFO 14 (6/20)
2022-06-08 09:46:19,120 INFO 15 (7/20)
2022-06-08 09:46:19,246 INFO 16 (8/20)
2022-06-08 09:46:19,369 INFO 17 (9/20)
2022-06-08 09:46:19,489 INFO 18 (10/20)
2022-06-08 09:46:19,627 INFO 2 (11/20)
2022-06-08 09:46:19,769 INFO 3 (12/20)
2022-06-08 09:46:19,920 INFO 4 (13/20)
2022-06-08 09:46:20,062 INFO 5 (14/20)
2022-06-08 09:46:20,189 INFO 6 (15/20)
2022-06-08 09:46:20,326 INFO 7 (16/20)
2022-06-08 09:46:20,485 INFO 8 (17/20)
2022-06-08 09:46:20,616 INFO 9 (18/20)
2022-06-08 09:46:20,771 INFO X (19/20)
2022-06-08 09:46:20,894 INFO Y (20/20)
/home/yxzhao/miniconda3/lib/python3.9/site-packages/fanc/architecture/domains.py:410: RuntimeWarning: divide by zero encountered in log2
  ins_matrix = np.log2(ins_matrix)

Moreover, our .hic were generated by jucer.

**Comment by kaukrise** [comment]
Hi,

Juicer files are multi-resolution - you must choose a resolution for FAN-C to work with manually. There is also a warning about this in the logs you posted, which tells you how:

```
UserWarning: No resolution chosen for Juicer Hic - using 2500000bp. Specify a custom resolution using <.hic file>@<resolution>
```

This is explained in more detail in the [FAN-C docs](https://fan-c.readthedocs.io/en/latest/fanc-executable/compatibility.html).

Since you did not specify a resolution, `2500000` was selected automatically. A window size of 40kb would therefore be smaller than a single pixel in the Hi-C matrix, which of course would not work. Please choose an appropriately high resolution (5kb, for example), if you want to use a 40kb window size.

Cheers,
Kai

**Comment by 80QvQ08** [comment]
Hello, FANC is amazing! I successfully used FANC to analyze A/B compartment. but i also encountered the same problem mentioned above when i want to run the TAD analysis with .hic generated by jucer, and i specified a resolution 50kb, The code I used and the feedback are listed below:

`fanc insulation Mpha.hic@50kb Mpha_50kb.insulation -w 50kb`

2024-11-25 20:16:38,792 INFO FAN-C version: 0.9.28
2024-11-25 20:16:39,124 INFO Chosen window sizes: 50000
2024-11-25 20:16:39,850 INFO Chr1 (1/11)
Traceback (most recent call last):
  File "/opt/software/python/bin/fanc", line 127, in <module>
    Fanc()
  File "/opt/software/python/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/opt/software/python/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 3801, in insulation
    _domain_scores(parser, input_file, output_file, output_format,
  File "/opt/software/python/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 3853, in _domain_scores
    scores = score_class.from_hic(matrix, file_name=output_file,
  File "/opt/software/python/lib/python3.8/site-packages/fanc/architecture/domains.py", line 342, in from_hic
    values_by_chromosome[w_ix][k] /= bin_window_size ** 2
ZeroDivisionError: division by zero
Closing remaining open files:Mpha_50kb.insulation...done

At the mean time, I also try to use fanc auto to generate .hic using fastq.gz data and validpair data produced by Hicpro, but I encountered the same error: ZeroDivisionError: division by zero.

Thank you very much for your time and assistance. I look forward to your guidance on this matter.
