### ISSUE TITLE
Issue in generating insulation score plot

### ISSUE THREAD

**Issue by Lucas446** [vaquerizaslab/fanc#117]
Hi, thanks for the great program !

I have encounter issue when I wanted to make a plot containing the insulation score.

Here is my workflow to process HiC data from Drosophila:
_1) Using HiC-pro:_ 
R1,R2.fastq > validpairs

_2) Using FAN-C: validpairs > .hic file_
`fanc auto {allValidPairs} {output} -g {DpnII_resfrag_dm6.bed}`

_3) Insulation score using 50kb.hic_
`fanc insulation -w 50kb 75kb 100kb 250kb 500kb 1mb 2mb -g 50kb.hic 50kb.ins`
The .ins file is created with no issue

_4) Plotting:_
`fancplot -o test.png 3R:1mb-32mb -p triangular 50kb.hic -m 4000000 -vmin 0 -vmax 0.05 -p scores 50kb.ins`

Here is what I get:
```
44,656 INFO Using non-interactive backend
18:45,351 INFO Found 1 regions
/usr/local/bin/fancplot:186: UserWarning: There was an error with plot 0, region 3R:1000000-32000000 (Traceback (most recent call last):
  File "/usr/local/bin/fancplot", line 169, in __init__
    fig, axes = gf.plot(plot_region)
  File "/usr/local/lib/python3.9/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/usr/local/lib/python3.9/site-packages/fanc/plotting/base_plotter.py", line 292, in plot
    plot_output = self._plot(region)
  File "/usr/local/lib/python3.9/site-packages/fanc/plotting/plotter.py", line 535, in _plot
    self.collection = self.ax.pcolormesh(x, y, np.ma.masked_invalid(self.hm.T),
  File "/usr/local/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 6058, in pcolormesh
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5568, in _pcolorargs
    raise TypeError('Dimensions of C %s are incompatible with'
TypeError: Dimensions of C (6, 621) are incompatible with X (622) and/or Y (6); see help(pcolormesh)
)
  warnings.warn("There was an error with plot {}, region {}:{}-{} ({})".format(i, region.chromosome,
2022-06-17 10:18:46,586 WARNING Dimensions of C (6, 621) are incompatible with X (622) and/or Y (6); see help(pcolormesh)
Closing remaining open files:sample_merged_50kb.hic...donesample_merged_50kb.hicinsulator_score.ins...done
```

I have been successfully able to plot the .hic file using:
`fancplot -o test.png 3R:1mb-32mb -p triangular 50kb.hic`

Thank you very much for your time, 
Best, 
Tanguy

**Comment by kaukrise** [comment]
Hi there,

thanks for reporting this. I am not sure what is going on, so let's first see if the insulation file looks okay. Can you run 

```
fanc insulation 50kb.ins
```

and see if all the window sizes are reported correctly?

Then, please, convert one of the resolutions to BigWig (or BED, whatever you prefer), and plot only that track:

```
fanc insulation 50kb.ins -w 100000 -o bw
```

This should generate 50kb.ins_100kb.bw. Then plot with

```
fancplot 3R:1mb-32mb -p line 50kb.ins_100kb.bw
```

Thanks!

**Comment by kaukrise** [comment]
Hmm, in that case I am not sure what the issue is. Can you try plotting with a simpler command, in a narrower window, please?

```
fancplot 3R:10mb-20mb -p scores 50kb.ins
```

**Comment by Lucas446** [comment]
`fancplot 3R:10mb-20mb -p scores 50kb.ins `

```
2022-06-17 11:27:40,990 INFO Found 1 regions
/usr/local/bin/fancplot:186: UserWarning: There was an error with plot 0, region 3R:10000000-20000000 (Traceback (most recent call last):
  File "/usr/local/bin/fancplot", line 169, in __init__
    fig, axes = gf.plot(plot_region)
  File "/usr/local/lib/python3.9/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/usr/local/lib/python3.9/site-packages/fanc/plotting/base_plotter.py", line 292, in plot
    plot_output = self._plot(region)
  File "/usr/local/lib/python3.9/site-packages/fanc/plotting/plotter.py", line 535, in _plot
    self.collection = self.ax.pcolormesh(x, y, np.ma.masked_invalid(self.hm.T),
  File "/usr/local/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 6058, in pcolormesh
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
  File "/usr/local/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5568, in _pcolorargs
    raise TypeError('Dimensions of C %s are incompatible with'
TypeError: Dimensions of C (6, 201) are incompatible with X (202) and/or Y (6); see help(pcolormesh)
)
  warnings.warn("There was an error with plot {}, region {}:{}-{} ({})".format(i, region.chromosome,
2022-06-17 11:27:41,110 WARNING Dimensions of C (6, 201) are incompatible with X (202) and/or Y (6); see help(pcolormesh)
Closing remaining open files:/Users/tlucas/Desktop/2_BIO_INFO_ANALYSIS/Hi-C/Hi-C_QC_NB_NextSeq/NB_St14/NextSeq500/NBs_27K_pulled_biotin_PFA_st14/FANC/TRY_input_allValidPairs/hic/binned/Github_help/sample_merged_50kb.ins...done
```

arf still the the same error. 

Do you know what is that:
` Dimensions of C (6, 201) are incompatible with X (202) and/or Y (6); see help(pcolormesh)`

Best

**Comment by kaukrise** [comment]
It is a matplotlib error regarding the function I am plotting the scores with. But I cannot tell what the root cause is. Would you be willing to share your insulation file with me, so I can do some debugging?

**Comment by Lucas446** [comment]
You can download the .hic and .ins file here:

https://urldefense.proofpoint.com/v2/url?u=https-3A__wetransfer.com_downloads_5680c1d86ac4a3c1bed81ad472a6601020220617153258_8b4f1a33f3b3b656101813b8306c87c520220617153324_40ab63&d=DwMFaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=At6JldAWLwFK-tW4Hco-b3zcZTnMeAXiMGDyn_G11g0&m=Jw_MabbyLB0Eu2ExOQ4XGzvRiBqUPvpupMF0oPsN8znaQFwrgj298PsGBfRnzKIE&s=uYedGxbBb9ObK35CC37mj8Egmg4rYdw_4G6P6jnBEo8&e=

Hope you can fix it :)

Thanks a lot, 
Best, 
Tanguy

**Comment by kaukrise** [comment]
Awesome, thanks a lot, can you try this beta version to see if it fixes your issue, please?

[fanc-0.9.25b1.tar.gz](https://github.com/vaquerizaslab/fanc/files/8928896/fanc-0.9.25b1.tar.gz)

You can install the archive directly using pip

```
pip install fanc-0.9.25b1.tar.gz
```

**Comment by Lucas446** [comment]
Hi, 

It is working great, I can plot the insulation score with your beta version ! Amazing :)

Thanks a lot, 

Best, 
Tanguy
