### ISSUE TITLE
from-txt produced error

### ISSUE THREAD

**Issue by BioEpi** [vaquerizaslab/fanc#121]
Hello,
    I am trying to convert HiC-Pro matrix to .hic using fanc from-txt, but I got the following errors:

2022-07-13 22:25:02,391 INFO FAN-C version: 0.9.24
Traceback (most recent call last):
  File "/data/anaconda3/envs/python38/lib/python3.8/site-packages/fanc/compatibility/txt.py", line 11, in load_contacts
    m = np.load(contacts_file_name)
  File "/data/anaconda3/envs/python38/lib/python3.8/site-packages/numpy/lib/npyio.py", line 445, in load
    raise ValueError("Cannot load file containing pickled data "
`ValueError: Cannot load file containing pickled data when allow_pickle=False`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/python38/bin/fanc", line 127, in <module>
    Fanc()
  File "/data/anaconda3/envs/python38/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/data/anaconda3/envs/python38/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 1827, in from_txt
    for source, sink, weight in load_contacts(contacts_file, ix_converter=ix_converter):
  File "/data/anaconda3/envs/python38/lib/python3.8/site-packages/fanc/compatibility/txt.py", line 39, in load_contacts
    source = ix_converter[fields[0]]
`KeyError: '0'`
Closing remaining open files:./1000000_iced.hic...done

do you know how to fix this issue?
Best,

**Comment by kaukrise** [comment]
Hi,

we don't have a function for APA scores, but using `--loop-strength` or `--tad-strength` you can write the relative enrichment of each component of the aggregate matrix to file, which is a similar concept, if I understand correctly.

Cheers
