### ISSUE TITLE
aggregate: pybedtools.cbedtools.MalformedBedLineError

### ISSUE THREAD

**Issue by sarah872** [vaquerizaslab/fanc#126]
Hi,
I want to run the `aggregate` module for the loops.
This is my command:

```
fanc loops hic/binned/R_5kb.hic loops.out -t 8
fanc loops loops.out -b loops.bedpe
# filtered
fanc loops loops.out filtered_loops.out --rh-filter -d 5 -o 5
fanc loops filtered_loops.out filtered_loops_merged.out -j --remove-singlets
fanc loops filtered_loops_merged.out -b filtered_loops_merged.bedpe

fanc aggregate hic/binned/R_5kb.hic filtered_loops_merged.bedpe filtered_loops_merged.bedpe.agg -p filtered_loops_merged.bedpe.agg.pdf --loops
```

My `filtered_loops_merged.bedpe` looks like this:
```
genome	2072003	2102997	genome	2467003	2495391	.	0.0
genome	-13968	18969	genome	2041031	2073969	.	0.0
genome	2237114	2267886	genome	2277114	2307886	.	0.0
genome	1528294	1576706	genome	1593294	1641706	.	0.0
genome	2255470	2329530	genome	2385470	2459530	.	0.0
genome	1432501	1452500	genome	1607501	1627500	.	0.0
genome	2276876	2328125	genome	2316876	2368125	.	0.0
```

I'm getting the following error:

```
2022-09-01 22:11:57,265 INFO FAN-C version: 0.9.24
2022-09-01 22:11:57,410 INFO Detected BEDPE. Running pairwise region extraction
Traceback (most recent call last):
  File "/apps/fanc/0.9.24/bin/fanc", line 127, in <module>
    Fanc()
  File "/apps/fanc/0.9.24/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/apps/fanc/0.9.24/lib/python3.10/site-packages/fanc/commands/fanc_commands.py", line 4783, in aggregate
    for region in regions.regions:
  File "/apps/fanc/0.9.24/lib/python3.10/site-packages/genomic_regions/regions.py", line 1449, in _region_iter
    for interval in self.intervals:
  File "pybedtools/cbedtools.pyx", line 835, in pybedtools.cbedtools.IntervalFile.__next__
pybedtools.cbedtools.MalformedBedLineError: malformed line: ['genome', '-13968', '18969', 'genome', '2041031', '2073969', '.', '0.0']
```

As expected, it works when I remove the negative values: `grep -v "-" filtered_loops_merged.bedpe`. I wonder why there are negative values at all?

**Comment by liz-is** [comment]
Hi, this seems to be the same issue as reported here: https://github.com/vaquerizaslab/fanc/issues/125 
This is due to the loop centroid calculation and you can set the negative values to zero.
