### ISSUE TITLE
Error in fancplot

### ISSUE THREAD

**Issue by Kurotakid** [vaquerizaslab/fanc#13]
Hi,
When I used a juicer .hic file as input in fancplot, I got the following errors:

```
[kurotaki ~/HiC/Juicer_data/GB6367]$fancplot chr8:119,729,676-121,763,375 -p square KO_MDP_rep2.hic@500000
2020-02-26 20:25:00,284 INFO Found 1 regions
failed to get the current screen resources
/home/kurotaki/miniconda3/bin/fancplot:157: UserWarning: There was an error with plot 0, region chr8:119729676-121763375 (Traceback (most recent call last):
  File "/home/kurotaki/miniconda3/bin/fancplot", line 139, in __init__
    fig, axes = gf.plot(plot_region)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/plotting/base_plotter.py", line 785, in plot
    plot_output = self._plot((x_region, y_region))
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/plotting/hic_plotter.py", line 296, in _plot
    self._refresh(region)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/plotting/hic_plotter.py", line 339, in _refresh
    self.current_matrix = self.hic_buffer.get_matrix(*region)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/plotting/hic_plotter.py", line 143, in get_matrix
    self._BUFFERING_STRATEGIES[self.buffering_strategy](self, *regions)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/plotting/hic_plotter.py", line 186, in _buffer_relative
    norm=self.norm, oe=self.oe, log=self.log)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/matrix.py", line 987, in matrix
    **kwargs)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/matrix.py", line 908, in regions_and_matrix_entries
    row_regions, col_regions, edges_iter = self.regions_and_edges(key, *args, **kwargs)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/matrix.py", line 813, in regions_and_edges
    row_regions = list(row_regions)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/compatibility/juicer.py", line 700, in _region_subset
    subset_ix, subset_start = self._region_start(region)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/compatibility/juicer.py", line 665, in _region_start
    offset_ix = self._chromosome_ix_offset(region.chromosome)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/fanc/compatibility/juicer.py", line 648, in _chromosome_ix_offset
    raise ValueError("Chromosome {} not in matrix.".format(target_chromosome))
ValueError: Chromosome chr8 not in matrix.
)
  tb))
2020-02-26 20:25:02,602 WARNING Chromosome chr8 not in matrix.
```
How can I overcome this?
Best,
Daisuke

**Comment by kaukrise** [comment]
Try

```
fancplot 8:119,729,676-121,763,375 -p square KO_MDP_rep2.hic@500000
```

**Comment by Kurotakid** [comment]
Thank you for your quick reply! I could generate a heat map.
Don't we need to add "chr" for specifying genome locations in the fancplot?

**Comment by kaukrise** [comment]
That depends on how the chromosomes are called in the file!

Juicer uses chromosome names without 'chr' prefix. FAN-C uses the reference names as defined in the genome FASTA or the restriction fragment.

If you have a mixture of datasets with different naming schemes, you can adjust how each plot handles the 'chr' prefix by using `--fix-chromosome`. So, the following should also work in your case:

```
fancplot chr8:119,729,676-121,763,375 -p square --fix-chromosome KO_MDP_rep2.hic@500000
```

**Comment by Kurotakid** [comment]
You are helpful!
Thanks.
