### ISSUE TITLE
error - Exceeded maximum attempts

### ISSUE THREAD

**Issue by yeroslaviz** [vaquerizaslab/fanc#130]
I'm running fanc on my cluster using a batch script (on SLRUM), as I have multiple samples to run. I'm doing it in an array, though I don't think this causes the problem.

I ran the example data set and it works fine, but now when I run my sample I get this error, which I can't really contect to anything in the workflow

```
Closing remaining open files:fanc/1082.conc/hic/1082.conc.hic...done
Traceback (most recent call last):
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/commands/fanc_commands.py", line 1609, in hic
    restore_coverage=restore_coverage)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/hic.py", line 427, in normalise
    bias_vector = kr_balancing(self, **kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/hic.py", line 876, in kr_balancing
    m_corrected, bias_vector_chromosome = correct_matrix(m, restore_coverage=restore_coverage)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/hic.py", line 921, in correct_matrix
    raise RuntimeError("Exceeded maximum attempts (%d)" % max_attempts)
RuntimeError: Exceeded maximum attempts (50)
Closing remaining open files:fanc/1082.conc/hic/binned/1082.conc_5kb.hic...donefanc/1082.conc/hic/1082.conc.hic...done
Traceback (most recent call last):
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/commands/fanc_commands.py", line 123, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/commands/auto.py", line 1290, in auto
    runner.run()
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/commands/auto.py", line 142, in run
    "Cancelling execution of all tasks.".format(task.id))
RuntimeError: Task 5ccd55f7-f766-4494-8385-f24422a79fe6 had non-zero exit status. Cancelling execution of all tasks.
```

Any ideas what causes this problem?
I also attach here the output of `fanc` for one of the samples.

thanks

Assa 

[fanc.job.82230.1.err.txt](https://github.com/vaquerizaslab/fanc/files/9640561/fanc.job.82230.1.err.txt)

**Comment by kaukrise** [comment]
Hi,

this sometimes happens with KR normalisation - often on very sparse matrices. You could try the ICE norm instead, which should give highly similar results.

Cheers,
Kai

**Comment by yeroslaviz** [comment]
Thanks, I'll give it a try

**Comment by yeroslaviz** [comment]
Setting the normalization to `ICE` solved the error. 
Just have a followup question. Looking at the output I have many line with a so-called ligation error. Can you tell me maybe what this means?

thanks for the help and for this great tool.

**Comment by kaukrise** [comment]
Can you please post the lines here?

**Comment by yeroslaviz** [comment]
it looks like that:

```
Ligation error   0% (0 of 51995862) |    | Elapsed Time: 0:00:00 ETA:  --:--:--
Ligation error   0% (6 of 51995862) |    | Elapsed Time: 0:00:00 ETA:  00:00:00
Ligation error   1% (519959 of 51995862) || Elapsed Time: 0:00:04 ETA:   0:07:29
Ligation error   2% (1039920 of 51995862) || Elapsed Time: 0:00:11 ETA:   0:11:20
Ligation error   3% (1559876 of 51995862) || Elapsed Time: 0:00:17 ETA:   0:09:39
Ligation error   4% (2079836 of 51995862) || Elapsed Time: 0:00:23 ETA:   0:09:15
Ligation error   5% (2599795 of 51995862) || Elapsed Time: 0:00:30 ETA:   0:11:09
Ligation error   6% (3119752 of 51995862) || Elapsed Time: 0:00:36 ETA:   0:09:17
Ligation error   7% (3639719 of 51995862) || Elapsed Time: 0:00:41 ETA:   0:07:26
Ligation error   8% (4159675 of 51995862) || Elapsed Time: 0:00:46 ETA:   0:08:59
Ligation error   9% (4679628 of 51995862) || Elapsed Time: 0:00:52 ETA:   0:09:00
Ligation error  10% (5199594 of 51995862) || Elapsed Time: 0:00:58 ETA:   0:08:50
Ligation error  11% (5719546 of 51995862) || Elapsed Time: 0:01:04 ETA:   0:08:39
Ligation error  12% (6239506 of 51995862) || Elapsed Time: 0:01:10 ETA:   0:08:34
Ligation error  13% (6759464 of 51995862) || Elapsed Time: 0:01:16 ETA:   0:08:26
Ligation error  14% (7279422 of 51995862) || Elapsed Time: 0:01:21 ETA:   0:07:10
Ligation error  15% (7799383 of 51995862) || Elapsed Time: 0:01:27 ETA:   0:08:29
Ligation error  16% (8319338 of 51995862) || Elapsed Time: 0:01:32 ETA:   0:07:42
Ligation error  17% (8839301 of 51995862) || Elapsed Time: 0:01:38 ETA:   0:08:29
Ligation error  18% (9359259 of 51995862) || Elapsed Time: 0:01:44 ETA:   0:08:15
Ligation error  19% (9879215 of 51995862) || Elapsed Time: 0:01:50 ETA:   0:07:30
Ligation error  20% (10399178 of 51995862) || Elapsed Time: 0:01:55 ETA:   0:06:01
Ligation error  21% (10919132 of 51995862) || Elapsed Time: 0:02:00 ETA:   0:07:16
Ligation error  22% (11439092 of 51995862) || Elapsed Time: 0:02:06 ETA:   0:07:19
Ligation error  23% (11959049 of 51995862) || Elapsed Time: 0:02:12 ETA:   0:08:38
Ligation error  24% (12479007 of 51995862) || Elapsed Time: 0:02:18 ETA:   0:07:06
Ligation error  25% (12998967 of 51995862) || Elapsed Time: 0:02:23 ETA:   0:05:44
Ligation error  26% (13518933 of 51995862) || Elapsed Time: 0:02:28 ETA:   0:06:48
Ligation error  27% (14038890 of 51995862) || Elapsed Time: 0:02:33 ETA:   0:06:13
Ligation error  28% (14558842 of 51995862) || Elapsed Time: 0:02:38 ETA:   0:06:13
Ligation error  29% (15078801 of 51995862) || Elapsed Time: 0:02:44 ETA:   0:06:30
Ligation error  30% (15598760 of 51995862) || Elapsed Time: 0:02:49 ETA:   0:06:30
Ligation error  31% (16118721 of 51995862) || Elapsed Time: 0:02:55 ETA:   0:06:17
Ligation error  32% (16638676 of 51995862) || Elapsed Time: 0:03:01 ETA:   0:06:38
Ligation error  33% (17158636 of 51995862) || Elapsed Time: 0:03:07 ETA:   0:06:28
Ligation error  34% (17678598 of 51995862) || Elapsed Time: 0:03:12 ETA:   0:06:09
Ligation error  35% (18198552 of 51995862) || Elapsed Time: 0:03:18 ETA:   0:06:45
Ligation error  36% (18718520 of 51995862) || Elapsed Time: 0:03:25 ETA:   0:06:44
Ligation error  37% (19238469 of 51995862) || Elapsed Time: 0:03:29 ETA:   0:04:39
Ligation error  38% (19758436 of 51995862) || Elapsed Time: 0:03:35 ETA:   0:06:15
Ligation error  39% (20278388 of 51995862) || Elapsed Time: 0:03:41 ETA:   0:05:38
Ligation error  40% (20798345 of 51995862) || Elapsed Time: 0:03:46 ETA:   0:05:22
Ligation error  41% (21318304 of 51995862) || Elapsed Time: 0:03:52 ETA:   0:05:27
Ligation error  42% (21838263 of 51995862) || Elapsed Time: 0:03:58 ETA:   0:05:55
Ligation error  43% (22358223 of 51995862) || Elapsed Time: 0:04:04 ETA:   0:05:53
Ligation error  44% (22878180 of 51995862) || Elapsed Time: 0:04:10 ETA:   0:05:42
Ligation error  45% (23398140 of 51995862) || Elapsed Time: 0:04:15 ETA:   0:04:44
Ligation error  46% (23918104 of 51995862) || Elapsed Time: 0:04:21 ETA:   0:05:05
Ligation error  47% (24438056 of 51995862) || Elapsed Time: 0:04:27 ETA:   0:05:01
Ligation error  48% (24958021 of 51995862) || Elapsed Time: 0:04:32 ETA:   0:04:59
Ligation error  49% (25477973 of 51995862) || Elapsed Time: 0:04:38 ETA:   0:04:56
Ligation error  50% (25997933 of 51995862) || Elapsed Time: 0:04:44 ETA:   0:04:45
Ligation error  51% (26517891 of 51995862) || Elapsed Time: 0:04:50 ETA:   0:04:37
Ligation error  52% (27037849 of 51995862) || Elapsed Time: 0:04:55 ETA:   0:04:26
Ligation error  53% (27557807 of 51995862) || Elapsed Time: 0:05:01 ETA:   0:04:29
Ligation error  54% (28077766 of 51995862) || Elapsed Time: 0:05:07 ETA:   0:04:25
Ligation error  55% (28597727 of 51995862) || Elapsed Time: 0:05:12 ETA:   0:04:14
Ligation error  56% (29117686 of 51995862) || Elapsed Time: 0:05:18 ETA:   0:03:57
Ligation error  57% (29637642 of 51995862) || Elapsed Time: 0:05:24 ETA:   0:04:24
Ligation error  58% (30157604 of 51995862) || Elapsed Time: 0:05:29 ETA:   0:03:36
Ligation error  59% (30677563 of 51995862) || Elapsed Time: 0:05:35 ETA:   0:03:44
Ligation error  60% (31197522 of 51995862) || Elapsed Time: 0:05:40 ETA:   0:03:38
Ligation error  61% (31717477 of 51995862) || Elapsed Time: 0:05:46 ETA:   0:03:38
Ligation error  62% (32237436 of 51995862) || Elapsed Time: 0:05:51 ETA:   0:03:35
Ligation error  63% (32757394 of 51995862) || Elapsed Time: 0:05:57 ETA:   0:03:24
Ligation error  64% (33277357 of 51995862) || Elapsed Time: 0:06:02 ETA:   0:03:06
Ligation error  65% (33797312 of 51995862) || Elapsed Time: 0:06:09 ETA:   0:04:03
Ligation error  66% (34317269 of 51995862) || Elapsed Time: 0:06:16 ETA:   0:03:53
Ligation error  67% (34837234 of 51995862) || Elapsed Time: 0:06:22 ETA:   0:03:29
Ligation error  68% (35357188 of 51995862) || Elapsed Time: 0:06:28 ETA:   0:02:50
Ligation error  69% (35877145 of 51995862) || Elapsed Time: 0:06:33 ETA:   0:02:49
Ligation error  70% (36397106 of 51995862) || Elapsed Time: 0:06:39 ETA:   0:02:59
Ligation error  71% (36917063 of 51995862) || Elapsed Time: 0:06:44 ETA:   0:02:33
Ligation error  72% (37437024 of 51995862) || Elapsed Time: 0:06:49 ETA:   0:02:22
Ligation error  73% (37956980 of 51995862) || Elapsed Time: 0:06:55 ETA:   0:02:20
Ligation error  74% (38476938 of 51995862) || Elapsed Time: 0:06:59 ETA:   0:02:01
Ligation error  75% (38996897 of 51995862) || Elapsed Time: 0:07:04 ETA:   0:02:09
Ligation error  76% (39516863 of 51995862) || Elapsed Time: 0:07:10 ETA:   0:02:11
Ligation error  77% (40036815 of 51995862) || Elapsed Time: 0:07:15 ETA:   0:02:04
Ligation error  78% (40556773 of 51995862) || Elapsed Time: 0:07:21 ETA:   0:01:58
Ligation error  79% (41076731 of 51995862) || Elapsed Time: 0:07:26 ETA:   0:01:50
Ligation error  80% (41596690 of 51995862) || Elapsed Time: 0:07:31 ETA:   0:01:46
Ligation error  81% (42116650 of 51995862) || Elapsed Time: 0:07:37 ETA:   0:01:39
Ligation error  82% (42636610 of 51995862) || Elapsed Time: 0:07:42 ETA:   0:01:32
Ligation error  83% (43156567 of 51995862) || Elapsed Time: 0:07:47 ETA:   0:01:28
Ligation error  84% (43676526 of 51995862) || Elapsed Time: 0:07:52 ETA:   0:01:24
Ligation error  85% (44196484 of 51995862) || Elapsed Time: 0:07:58 ETA:   0:01:23
Ligation error  86% (44716442 of 51995862) || Elapsed Time: 0:08:03 ETA:   0:01:19
Ligation error  87% (45236403 of 51995862) || Elapsed Time: 0:08:09 ETA:   0:01:08
Ligation error  88% (45756360 of 51995862) || Elapsed Time: 0:08:14 ETA:   0:01:05
Ligation error  89% (46276323 of 51995862) || Elapsed Time: 0:08:19 ETA:   0:00:56
Ligation error  90% (46796284 of 51995862) || Elapsed Time: 0:08:25 ETA:   0:00:52
Ligation error  91% (47316238 of 51995862) || Elapsed Time: 0:08:30 ETA:   0:00:46
Ligation error  92% (47836194 of 51995862) || Elapsed Time: 0:08:35 ETA:   0:00:42
Ligation error  93% (48356152 of 51995862) || Elapsed Time: 0:08:40 ETA:   0:00:36
Ligation error  94% (48876116 of 51995862) || Elapsed Time: 0:08:45 ETA:   0:00:31
Ligation error  95% (49396074 of 51995862) || Elapsed Time: 0:08:51 ETA:   0:00:26
Ligation error  96% (49916038 of 51995862) || Elapsed Time: 0:08:56 ETA:   0:00:20
Ligation error  97% (50435994 of 51995862) || Elapsed Time: 0:09:01 ETA:   0:00:14
Ligation error  98% (50955946 of 51995862) || Elapsed Time: 0:09:06 ETA:   0:00:09
Ligation error  99% (51475904 of 51995862) || Elapsed Time: 0:09:11 ETA:   0:00:04
Ligation error 100% (51995862 of 51995862) || Elapsed Time: 0:09:16 Time:  0:09:16
```

**Comment by kaukrise** [comment]
This is not an error, it *calculates* the ligation error. See here: https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_modular_steps.html#fanc-pairs-generating-and-filtering-read-pairs
