### ISSUE TITLE
fancplot MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by yeroslaviz** [vaquerizaslab/fanc#132]
when trying to plot the insulation plots I get the following warning

```
$ fancplot -o architecture/domains/fanc_example_100kb_tads_insulation.png chr18:18mb-28mb \
>      -p triangular output/hic/binned/fanc_example_100kb.hic -m 4000000 -vmin 0 -vmax 0.05 \
>      -p scores architecture/domains/fanc_example_100kb.insulation_imputed -vmin -1 -vmax 1
2022-10-04 11:02:08,171 INFO Using non-interactive backend
2022-10-04 11:02:08,521 INFO Found 1 regions
/fs/home/yeroslaviz/.local/lib/python3.6/site-packages/fanc/plotting/plotter.py:537: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  norm=self._map_norm, **self.plot_kwargs)
Closing remaining open files:output/hic/binned/fanc_example_100kb.hic...donearchitecture/domains/fanc_example_100kb.insulation_imputed...done
```

It still creates the plot and this is just a warning (for now), but I guess this should be updated soon.

Assa

P.S.

I'm running `fanc -V 0.9.25b1`

**Comment by kaukrise** [comment]
Hi, I ran the tutorial on a fresh installation of FAN-C and could not reproduce the issue you are seeing. I neither get a `MatplotlibDeprecationWarning`, nor do I observe the "shift" in scores that is visible in the image you posted.

What is your `matplotlib` version?

**Comment by yeroslaviz** [comment]
When running it within my conda environment I have python 3.7.13 and matplotlib  3.5.3. Here I get this message with the same command:

```
fancplot -o architecture/domains/fanc_example_100kb_tads_insulation.png chr18:18mb-28mb          -p triangular output/hic/binned/fanc_example_100kb.hic -m 4000000 -vmin 0 -vmax 0.05          -p scores architecture/domains/fanc_example_100kb.insulation_imputed -vmin -1 -vmax 1
2022-10-19 21:04:58,755 INFO Using non-interactive backend
2022-10-19 21:04:59,550 INFO Found 1 regions
/fs/home/yeroslaviz/miniconda3/envs/fanc/bin/fancplot:164: UserWarning: There was an error with plot 0, region chr18:18000000-28000000 (Traceback (most recent call last):
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/bin/fancplot", line 144, in __init__
    fig, axes = gf.plot(plot_region)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/plotting/base_plotter.py", line 292, in plot
    plot_output = self._plot(region)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/fanc/plotting/plotter.py", line 537, in _plot
    norm=self._map_norm, **self.plot_kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6065, in pcolormesh
    shading=shading, kwargs=kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/fanc/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5576, in _pcolorargs
    C.shape, Nx, Ny, funcname))
TypeError: Dimensions of C (7, 101) are incompatible with X (102) and/or Y (7); see help(pcolormesh)
)
  tb))
2022-10-19 21:04:59,868 WARNING Dimensions of C (7, 101) are incompatible with X (102) and/or Y (7); see help(pcolormesh)
Closing remaining open files:architecture/domains/fanc_example_100kb.insulation_imputed...doneoutput/hic/binned/fanc_example_100kb.hic...done
```

When running it with the pip-installed version I get this error:

```
 fancplot -o architecture/domains/fanc_example_100kb_tads_insulation.png chr18:18mb-28mb \
>          -p triangular output/hic/binned/fanc_example_100kb.hic -m 4000000 -vmin 0 -vmax 0.05 \
>          -p scores architecture/domains/fanc_example_100kb.insulation_imputed -vmin -1 -vmax 1
2022-10-19 21:13:41,719 INFO Using non-interactive backend
2022-10-19 21:13:42,067 INFO Found 1 regions
/fs/home/yeroslaviz/.local/lib/python3.6/site-packages/fanc/plotting/plotter.py:537: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  norm=self._map_norm, **self.plot_kwargs)
Closing remaining open files:architecture/domains/fanc_example_100kb.insulation_imputed...doneoutput/hic/binned/fanc_example_100kb.hic...done
(base) python --version
Python 3.7.12
(base) python 
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'3.5.3'
```

I truly don't get it. 

I would appreciate the help.

**Comment by kaukrise** [comment]
I just downgraded my local matplotlib version to `3.5.3`, but I still don't see the issue you are getting. I am wondering whether the `fancplot` version you are accessing via the command line somehow uses the wrong packages. We've seen similar issues with conda before.

Can you please try the following version? 

[fanc-0.9.26b1.tar.gz](https://github.com/vaquerizaslab/fanc/files/9823754/fanc-0.9.26b1.tar.gz)

It should print the line

```
Matplotlib version: 3.5.3
```

when you run the plotting command.

**Comment by yeroslaviz** [comment]
Thanks a lot. That seems to solve the problem.

I have installed it within my conda env using `pip install -e .` and now I have in the conda the newest version, as well as a correct plot. 

thanks for the help
(Can you tell me, what was the change you did?)

P.S.
You mentioning a newer, much faster fan-c version in the dev track. Does it works now good enough to test?

**Comment by kaukrise** [comment]
> (Can you tell me, what was the change you did?)

Compared to 0.9.25 I did nothing - I merely put the debug message about the Matplotlib version in there. This indicates it might have been your local environment, as suspected.

> P.S. You mentioning a newer, much faster fan-c version in the dev track. Does it works now good enough to test?

You are actually the first person to ever enquire about this version - it seems that most people were content with the current speed. There are a lot of bug fixes in `main` that I did not port to the `dev` branch, because the effort of maintaining it greatly outweighed demand. If I have some time on my hands at some point, I will try to update `dev`, but it won't be in the near future.

**Comment by yeroslaviz** [comment]
no worries, thanks

I might suggest that you recommend creating a conda env with the needed, clean python installation and than installing the fan-c tool locally using `pip`.
In my opinion this would be the easiest method to get a clean environment, which has all what the tools needs. Especially if people are working on a cluster with different modalities and no root premissions.

thanks for all the help.

**Comment by kaukrise** [comment]
I have updated the installation instructions in the docs to clarify that we no longer support Bioconda, and that we strongly recommend using fresh Python virtual environments.
