### ISSUE TITLE
Normalize matrix from fanc compare?

### ISSUE THREAD

**Issue by joshuak94** [vaquerizaslab/fanc#139]
Hello! Happy new year!

I had to use fanc compare using the -u (unnormalized) flag to compare two .hic files. Now I have an unnormalized matrix result and would like to know if there is any way to re-normalize the matrix, either via the command line or the python API.

Thank you!

**Comment by joshuak94** [comment]
Note, I am trying to do this via the python API and am running into the following issue:

```python
import fanc
from fanc.hic import kr_balancing
unnormalized_matrix = fanc.load("unnormalized.matrix")
normalized_matrix = ice_balancing(hic, whole_matrix=False, restore_coverage=True)
```
`OSError: attempt to write over a file opened in read-only mode`

I've narrowed it down to the following:
```python
import fanc
from fanc.hic import kr_balancing
unnormalized_matrix = fanc.load("unnormalized.matrix")
# This part works.
hic_norm, bias_norm = correct_matrix(unnormalized_matrix.matrix(norm=False), restore_coverage=True)
# This part doesn't.
hic.region_data('bias', bias_norm)
```
Full error:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/mambaforge/envs/fanc/lib/python3.10/site-packages/fanc/hic.py", line 893, in kr_balancing
    hic.region_data('bias', bias_vector)
  File "/home/user/mambaforge/envs/fanc/lib/python3.10/site-packages/fanc/matrix.py", line 2451, in region_data
    data = RegionPairsTable.region_data(self, key, value)
  File "/home/user/mambaforge/envs/fanc/lib/python3.10/site-packages/fanc/regions.py", line 681, in region_data
    row[key] = value[i]
  File "tables/tableextension.pyx", line 1563, in tables.tableextension.Row.__setitem__
OSError: attempt to write over a file opened in read-only mode
`
Which was taken from [here](https://github.com/vaquerizaslab/fanc/blob/3c32c52ed1fa4b50085938038e71ead9bb826c5a/fanc/hic.py#L893).

I guess that the load function is for some reason opening the matrix file in read-only mode and thus cannot write the normalized matrix in place. Any workarounds/advice is much appreciated.

**Comment by kaukrise** [comment]
I'm on holiday, so apologies for being brief

```python
unnormalized_matrix = fanc.load("unnormalized.matrix", mode='a')
```

should work

**Comment by joshuak94** [comment]
Yes, I realized that it was loading with read only by default. Thank you! Sorry to disturb your holidays. One more question: Would the following code a) load the unnormalized matrix and then b) normalize it in place, and then c) save the normalized matrix to the same file?

```python3
import fanc
from fanc.hic import kr_balancing
unnormalized_matrix = fanc.load("unnormalized.matrix", mode='a')
normalized_matrix = kr_balancing(hic, whole_matrix=False, restore_coverage=True)
exit()
```

**Comment by kaukrise** [comment]
Normalisation is done in place and you should close the file explicitly, so changes are guaranteed to be written to file

```python
import fanc
from fanc.hic import kr_balancing
matrix = fanc.load("unnormalized.matrix", mode='a')
kr_balancing(matrix, whole_matrix=False, restore_coverage=True)
matrix.close()
```

**Comment by joshuak94** [comment]
Thank you for the help!

I noticed that my unnormalized and normalized matrices look very similar to one another. For context, I am first subtracting two hic maps as such:
```sh
fanc compare -S -c diff -u matrix1.hic matrix2.hic unnormalized.matrix
```
Matrix 1 and 2 have been downsampled to the same number of valid pairs. 

Then I normalize the matrix as discussed.

However, the resulting maps look almost identical. Is this a result of the subtraction done earlier?

**Comment by kaukrise** [comment]
Hey, this might be related to #140. I need to do some tests myself when I am back at the computer next week.

I'd just like to note that I think your approach is not valid. The standard normalisation methods (ICE, KR) assume equal coverage of each bin. After subtracting matrices, this assumption is no longer valid. Typically, comparison matrices are not re-normalised.

**Comment by joshuak94** [comment]
Hi! I was wondering if it was possible to call loops on the resulting matrix after comparing two hic matrices. Currently I get the following error:
```sh
2023-01-25 10:13:53,181 INFO FAN-C version: 0.9.25
2023-01-25 10:13:54,040 INFO Calculating intra-chromosomal expected values...
2023-01-25 10:13:54,042 INFO Done.
2023-01-25 10:13:54,043 INFO Initial parameter values: p=4, w=7
2023-01-25 10:13:54,043 INFO Obtaining bias vector...
Traceback (most recent call last):
  File "/home/user/mambaforge/envs/fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/user/mambaforge/envs/fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/user/mambaforge/envs/fanc/lib/python3.10/site-packages/fanc/commands/fanc_commands.py", line 3011, in loops
    peaks = pk.call_peaks(matrix, chromosome_pairs=chromosome_pairs, file_name=o)
  File "/home/user/mambaforge/envs/fanc/lib/python3.10/site-packages/fanc/peaks.py", line 1243, in call_peaks
    c = hic.bias_vector()
AttributeError: 'DifferenceMatrix' object has no attribute 'bias_vector'
```
