### ISSUE TITLE
auto.py index out of range

### ISSUE THREAD

**Issue by alphataubio** [vaquerizaslab/fanc#172]
i get the following error trying to run fanc auto:

mitch@macmini _hic % fanc auto SRR027956.fastq -i /Users/mitch/_hic/hg18_chr14.fa -g hg18_chr14.bed .   
2023-10-06 11:17:09,460 INFO FAN-C version: 0.9.27
2023-10-06 11:17:09,462 INFO Getting regions
2023-10-06 11:17:09,463 INFO Output folder: ./
2023-10-06 11:17:09,463 INFO Input files: SRR027956.fastq
2023-10-06 11:17:09,463 INFO Input file types: fastq
2023-10-06 11:17:09,463 INFO Final basename: SRR027956 (you can change this with the -n option!)
2023-10-06 11:17:09,463 INFO Creating output folders...
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 127, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/Users/mitch/Library/Python/3.9/lib/python/site-packages/fanc/commands/fanc_commands.py", line 123, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/Users/mitch/Library/Python/3.9/lib/python/site-packages/fanc/commands/auto.py", line 1097, in auto
    if not file_types[i + 1] == 'sam':
IndexError: list index out of range

**Comment by kaukrise** [comment]
You need to supply two FASTQ files, or it is assumed you are using mapped SAM/BAM input. Please have a look at the example in the [docs](https://fan-c.readthedocs.io/en/latest/getting_started.html#example-analysis).
