### ISSUE TITLE
fanc boundaries: AttributeError: 'Bed' object has no attribute 'close'

### ISSUE THREAD

**Issue by prometheusloong** [vaquerizaslab/fanc#183]
Hi,

When i excute the command `fanc boundaries ${hic}/${a}.fanc/${l}_${w}.bed ${hic}/${a}.fanc/${l}.${w}.boundaries -w ${w} -s 0.7`, I got the below error. The ${hic}/${a}.fanc/${l}_${w}.bed is from ·`fanc insulation`. Could you please help me debug the error? Thank you!

fanc version is 0.9.23

`2024-03-18 20:50:45,078 INFO FAN-C version: 0.9.23
/public/home/zcyu/software/anaconda3/envs/fanc/lib/python3.7/site-packages/fanc/tools/matrix.py:76: UserWarning: Warning: converting a masked element to nan.
  delta[i] = np.ma.mean(x[down_slice] - x[i]) - np.ma.mean(x[up_slice] - x[i])
2024-03-18 20:51:08,380 INFO Found 9412 raw peaks
2024-03-18 20:51:08,777 INFO Found 2565 boundaries
Traceback (most recent call last):
  File "/public/home/zcyu/software/anaconda3/envs/fanc/bin/fanc", line 127, in <module>
    Fanc()
  File "/public/home/zcyu/software/anaconda3/envs/fanc/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/public/home/zcyu/software/anaconda3/envs/fanc/lib/python3.7/site-packages/fanc/commands/fanc_commands.py", line 3322, in boundaries
    insulation.close()
AttributeError: 'Bed' object has no attribute 'close'`

**Comment by kaukrise** [comment]
That was a bug when calling boundaries from BED file. It should not have affected the output, since it is the last operation in the command. Here is a version with a fix, could you test it, please?

[fanc-0.9.28b1.tar.gz](https://github.com/vaquerizaslab/fanc/files/14646237/fanc-0.9.28b1.tar.gz)

**Comment by joshuak94** [comment]
Hi Kai,

I tried to download the fix, but I'm still getting the same error. I generated insulation score bed files using HiC maps from an older version of FANC, which worked fine. But the boundary part keeps giving me the above mentioned error.

Edit: I realized I hadn't properly replaced the older version I had with the download. It works!
