### ISSUE TITLE
fancplot layer: AttributeError: 'Bed' object has no attribute '_parameters'

### ISSUE THREAD

**Issue by jmsanper** [vaquerizaslab/fanc#185]
Hi,
I'm trying to plot some boundaries from bed files that used to work with fancplot -p layer, but I'm getting this error:

2024-04-01 16:05:55,420 INFO Using non-interactive backend
Traceback (most recent call last):
  File "/Users/josemaria/miniconda3/bin/fancplot", line 261, in <module>
    FancPlot()
  File "/Users/josemaria/miniconda3/bin/fancplot", line 113, in __init__
    plot, plot_args = plot_method(args)
  File "/Users/josemaria/miniconda3/lib/python3.10/site-packages/fanc/commands/fancplot_commands.py", line 132, in scores
    data_selection = array._parameters
AttributeError: 'Bed' object has no attribute '_parameters'

Bed files used were generated with fanc boundaries, of course.
Could you please help me with this issue?
Thank you!

**Comment by jmsanper** [comment]
Hi again,
I realized that the problem was that I was trying to plot insulation scores calling to a bed file with a single window size and '-p scores' only accepts the insulation object as input.
Sorry!
