### ISSUE TITLE
pairs object from 4D Nucleome pairs file

### ISSUE THREAD

**Issue by tereski** [vaquerizaslab/fanc#19]
Hi,
I have instanlled fanc 0.81.31. I am very enthusiastic to see coverage plot (--marginals-plot) of the data of my interest (data from 4DNucleome portal). However, I am not able to create pairs object from 4D Nucleome pairs file.

```
fanc pairs 4DNFIQL5L5I3.pairs ./output/proper_pairs.pairs -g ./restriction_fragments_DpnII_hg38.bed

2020-06-26 12:58:47,981 INFO Getting genome regions (fragments or bins)
2020-06-26 12:58:47,981 INFO Getting regions
2020-06-26 12:58:47,995 INFO Two arguments detected, assuming HiC-Pro or 4D Nucleome input.
Traceback (most recent call last):
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 983, in pairs
    sb = FourDNucleomePairGenerator(input_file)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/pairs.py", line 653, in __init__
    for i, name in columns_field.split():
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tszczep/.local/bin/fanc", line 124, in <module>
    Fanc()
  File "/home/tszczep/.local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 986, in pairs
    sb = HicProPairGenerator(input_file)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/pairs.py", line 622, in __init__
    chr2_field=4, pos2_field=5, strand2_field=6)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/pairs.py", line 572, in __init__
    int(fields[pos2_field])
ValueError: invalid literal for int() with base 10: '+'
```
I made a testing file from this 4DN file. Here it is:

```
## pairs format v1.0.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#genome_assembly: unknown
#chromsize: chr1 248956422
#chromsize: chr2 242193529
#chromsize: chr3 198295559
#columns: readID chrom1 pos1 chrom2 pos2 strand1 strand2 pair_type frag1 frag2
K00284:70:HKG22BBXX:5:1127:25022:31453	chr1	10298	chr1	25266563	+	-	LL	0	69472
K00284:70:HKG22BBXX:2:1205:1205:11073	chr1	30899	chr1	228183613	-	+	LL	43	531295
K00284:70:HKG22BBXX:3:2121:8846:29800	chr1	30900	chr1	2078072	-	+	LL	43	4831
K00284:70:HKG22BBXX:1:2205:2351:28885	chr1	30903	chr1	213986772	-	+	LL	43	496325
```

How can I solve this? Can I modify 4DN pairs file somehow to be handled by fanc?

**Comment by kaukrise** [comment]
Hi,
thank you for bringing this to our attention. I have uploaded a new version (`0.8.32`) which you can upgrade via `pip`. This works work the example file you have provided.

Also, I just wanted to note that your column headers should be `chr1` and `chr2`, and not `chrom1` and `chrom2`, at least according to the official format specification. But I have written our parser to be more lenient, so it works with the file as you sent it.

**Comment by tereski** [comment]
Thank you very much for the quick solution! I have installed 0.8.32 version and produced pairs object. However, when I was using it to produce hic matrix another error occurred.
This is the output from running the same test file. I agree it has weird, incorrect column names (chrom1 instead of chr1) but this is what I found in 4DN pairs file.
```
fanc hic ./output/proper_pairs.pairs ./output/test.hic -b 40k --marginals-plot ./output/marginals-plot.pdf --subset chr1 -s ./output/statistics.test_hic.txt --statistics-plot ./output/statistics-plot.test_hic.pdf --chromosomes chr1 -t 60 -tmp
2020-06-26 19:51:48,558 INFO Converting Pairs files
2020-06-26 19:51:48,580 INFO Converting /tmp/tmp6xktviej.pairs to Hic
Hi-C convert 100% (4 of 4) |################################################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
2020-06-26 19:53:30,931 INFO Binning Hic file (40000)
2020-06-26 19:53:30,931 INFO Constructing binned genome...
2020-06-26 19:54:22,485 INFO Binning edges...
2020-06-26 19:54:22,609 INFO Binning Hi-C contacts
2020-06-26 19:55:20,485 INFO Launching processes
2020-06-26 19:55:50,236 INFO Submitting partitions
2020-06-26 19:55:50,324 INFO Collecting results
Binning  49% (422 of 861) |#######################################################################                                                                          | Elapsed Time: 0:36:38 ETA:   0:31:37
Traceback (most recent call last):
  File "/home/tszczep/.local/bin/fanc", line 124, in <module>
    Fanc()
  File "/home/tszczep/.local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 1435, in hic
    threads=threads, chromosomes=limit_chromosomes)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/hic.py", line 352, in bin
    hic.load_from_hic(self, threads=threads, chromosomes=chromosomes)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/hic.py", line 305, in load_from_hic
    raise out
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 6: invalid continuation byte
Closing remaining open files:/tmp/tmp1fm0tavx.hic...done/tmp/tmpvvt4kavc.hic...done
```

**Comment by kaukrise** [comment]
I have not seen this error before. It is surprising that it happens in the middle of binning. When you run the same command again, does it crash at the same position?

**Comment by tereski** [comment]
Yes, it crashed again at the same position.
```
fanc hic ./output/proper_pairs.pairs ./output/test.hic -b 40k --marginals-plot ./output/marginals-plot.pdf --subset chr1 -s ./output/statistics.test_hic.txt --statistics-plot ./output/statistics-plot.test_hic.pdf --chromosomes chr1 -t 60 -tmp
2020-06-26 23:13:22,564 INFO Converting Pairs files
2020-06-26 23:13:22,584 INFO Converting /tmp/tmpg06o8zpp.pairs to Hic
Hi-C convert 100% (4 of 4) |################################################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
2020-06-26 23:15:07,461 INFO Binning Hic file (40000)
2020-06-26 23:15:07,461 INFO Constructing binned genome...
2020-06-26 23:15:59,982 INFO Binning edges...
2020-06-26 23:16:00,105 INFO Binning Hi-C contacts
2020-06-26 23:16:58,388 INFO Launching processes
2020-06-26 23:17:28,376 INFO Submitting partitions
2020-06-26 23:17:28,463 INFO Collecting results
Binning  49% (422 of 861) |#######################################################################                                                                          | Elapsed Time: 0:37:02 ETA:   0:29:06
Traceback (most recent call last):
  File "/home/tszczep/.local/bin/fanc", line 124, in <module>
    Fanc()
  File "/home/tszczep/.local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 1435, in hic
    threads=threads, chromosomes=limit_chromosomes)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/hic.py", line 352, in bin
    hic.load_from_hic(self, threads=threads, chromosomes=chromosomes)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/hic.py", line 305, in load_from_hic
    raise out
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 6: invalid continuation byte
Closing remaining open files:/tmp/tmpwnac3y9b.hic...done/tmp/tmpe_qhvbkh.hic...done
```

**Comment by kaukrise** [comment]
Thanks again. I suspect the `msgpack` package may be the root cause. It is possible that your default encoding is not `utf-8`, which is causing the issue. `msgpack` recently reached `1.0.0`, where it enforces `utf-8` - can you try upgrading to the latest version and see if the issue persists?

```
pip install --upgrade msgpack
```

If this does not solve the issue, can you see if you can reproduce the problem with the [FAN-C sample files](https://vaquerizaslab.github.io/fanc/getting_started.html#example-analysis)? Thank you!

**Comment by tereski** [comment]
Thanks. My msgpack is updated to 1.0.0 There is no problem with processing FAN-C sample file. I have narrow the problem to two samples files the first one is proccessed correctly, the second one gives the error:
```
2020-08-12 13:36:55,087 INFO Getting genome regions (fragments or bins)
2020-08-12 13:36:55,371 INFO Getting regions
2020-08-12 13:36:55,373 INFO Two arguments detected, assuming HiC-Pro or 4D Nucleome input.
2020-08-12 13:40:00,253 INFO Done saving read pairs.
Buffers 100% (6 of 6) |##########################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
2020-08-12 13:40:00,501 INFO Updating region mappability
Mappability 100% (14 of 14) |####################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
2020-08-12 13:42:03,955 INFO Done adding pairs.
2020-08-12 13:42:04,324 INFO Saving statistics...
2020-08-12 13:42:11,329 INFO All done.
2020-08-12 13:42:11,330 INFO Command completed, sending email...
2020-08-12 13:42:14,582 INFO Converting Pairs files
2020-08-12 13:42:14,634 INFO Converting ./output/test_wrong_chr8.proper.pairs to Hic
Hi-C convert 100% (14 of 14) |###################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
2020-08-12 13:43:57,304 INFO Binning Hic file (40000)
2020-08-12 13:43:57,304 INFO Constructing binned genome...
2020-08-12 13:44:49,095 INFO Binning edges...
2020-08-12 13:44:49,231 INFO Binning Hi-C contacts
2020-08-12 13:45:46,171 INFO Launching processes
2020-08-12 13:46:07,409 INFO Submitting partitions
2020-08-12 13:46:07,475 INFO Collecting results
Binning  80% (689 of 861) |#################################################################################                     | Elapsed Time: 0:52:15 ETA:   0:03:08
2020-08-12 14:39:00,185 INFO Command failed, sending email...
Traceback (most recent call last):
  File "/home/tszczep/.local/bin/fanc", line 124, in <module>
    Fanc()
  File "/home/tszczep/.local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 1435, in hic
    threads=threads, chromosomes=limit_chromosomes)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/hic.py", line 352, in bin
    hic.load_from_hic(self, threads=threads, chromosomes=chromosomes)
  File "/home/tszczep/.local/lib/python3.6/site-packages/fanc/hic.py", line 305, in load_from_hic
    raise out
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 20: invalid start byte
Closing remaining open files:/tmp/tmphlb7nmh2.hic...done./output/test_wrong_chr8.hic...done
```
Example file that is processed corectly:
```
## pairs format v1.0.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#genome_assembly: unknown
#chromsize: chr3 198295559
#chromsize: chr8 145138636
#columns: readID chrom1 pos1 chrom2 pos2 strand1 strand2 pair_type frag1 frag2
K00284:70:HKG22BBXX:4:1225:21065:29448  chr3    55542913        chr8    40713635        +       +       LL      139385  102747
K00284:70:HKG22BBXX:5:2121:15666:33141  chr3    55542914        chr8    32475219        +       -       LL      139385  81601
K00284:70:HKG22BBXX:2:1213:30299:22239  chr3    55542922        chr8    142637799       +       -       LL      139385  343830
K00284:70:HKG22BBXX:8:2122:14143:13166  chr3    55542934        chr8    143128231       +       +       LL      139385  344961
K00284:68:HKF5WBBXX:7:1105:9019:27742   chr3    55542945        chr8    5718454 +       -       LL      139385  13050
K00284:70:HKG22BBXX:5:1225:2473:20234   chr3    55542960        chr8    51052046        +       +       LL      139385  124890
K00284:70:HKG22BBXX:4:2228:5041:39664   chr3    55543028        chr8    130451309       -       +       LL      139386  314691
K00284:70:HKG22BBXX:5:2113:18162:13271  chr3    55543048        chr8    8292943 -       +       LL      139386  19535
K00284:68:HKF5WBBXX:7:1117:4320:44746   chr3    55543054        chr8    13408487        -       -       LL      139386  33009
K00284:70:HKG22BBXX:7:2105:27773:19900  chr3    55543057        chr8    110217859       -       -       LL      139386  266645
K00284:68:HKF5WBBXX:7:2210:1326:40895   chr3    55543070        chr8    10946478        -       +       LL      139386  26608
K00284:70:HKG22BBXX:2:1109:26494:19935  chr3    55543077        chr8    92613971        -       +       LL      139386  223248
K00284:70:HKG22BBXX:6:1220:15950:13834  chr3    55543086        chr8    35644471        -       +       LL      139386  89560
K00284:70:HKG22BBXX:1:2125:3407:11266   chr3    55543106        chr8    3960153 -       -       LL      139386  9097

```
Example file that gives the error:
```
## pairs format v1.0.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#genome_assembly: unknown
#chromsize: chr3 198295559
#chromsize: chr8 145138636
#columns: readID chrom1 pos1 chrom2 pos2 strand1 strand2 pair_type frag1 frag2
K00284:70:HKG22BBXX:8:1217:19806:2299   chr3    55553495        chr8    10049243        +       -       LL      139406  24319
K00284:68:HKF5WBBXX:7:2206:24819:11513  chr3    55553530        chr8    34286523        -       -       LL      139406  86322
K00284:70:HKG22BBXX:3:1205:8643:8629    chr3    55553612        chr8    82035105        +       -       LL      139408  199214
K00284:70:HKG22BBXX:6:2123:10713:32508  chr3    55553635        chr8    22094299        +       -       LL      139408  54168
K00284:70:HKG22BBXX:6:2108:7060:25369   chr3    55553670        chr8    115420224       -       +       LL      139408  277513
K00284:70:HKG22BBXX:2:2202:11951:11759  chr3    55553686        chr8    76965081        -       -       LL      139408  187556
K00284:70:HKG22BBXX:1:1222:7791:34899   chr3    55553700        chr8    103767576       +       -       LL      139408  251843
K00284:68:HKF5WBBXX:7:1105:24688:34108  chr3    55553735        chr8    143673658       -       -       LL      139409  346208
K00284:68:HKF5WBBXX:7:1217:6959:39998   chr3    55553736        chr8    8870742 -       -       LL      139409  21161
K00284:70:HKG22BBXX:2:2108:16843:26283  chr3    55553736        chr8    35542102        -       -       LL      139409  89285
K00284:70:HKG22BBXX:3:1111:14722:8928   chr3    55553838        chr8    58207155        -       +       LL      139409  142351
K00284:70:HKG22BBXX:2:2211:31801:13552  chr3    55553860        chr8    57254846        -       -       LL      139409  140138
K00284:70:HKG22BBXX:4:1105:14986:34319  chr3    55553874        chr8    140650119       -       -       LL      139409  339464
K00284:70:HKG22BBXX:2:1220:15990:37079  chr3    55553877        chr8    43243893        -       +       LL      139409  110073

```
Any ideas what may be the source of the error?

**Comment by tereski** [comment]
Does anyone have the same error with the one file but not the other? Could you please check them?

**Comment by kaukrise** [comment]
Hi, thank you for the reminder, this got lost in my inbox. Apologies for that!

I ran your example files with FAN-C `0.9.2`, and both of your examples work without issues. At first I thought it might be an unexpected symbol in your second example file, but since this is happening during binning, I doubt that is the case.

Does this also happen if you copy-paste the contents of the second file from your previous post into a fresh file and run it again?

**Comment by tereski** [comment]
Juhuuuu!! FAN-C upgrade to 0.9.2 solved this issue! Both test files and the original file were processed correctly. Thank you for upgrading FAN-C.

**Comment by kaukrise** [comment]
Great, thank you for the update
