### ISSUE TITLE
fanc pca error

### ISSUE THREAD

**Issue by Rseq** [vaquerizaslab/fanc#21]
Hi many thanks for developing this tool. 
It is quite practical and good. However, I'm receiving an error in pca subcommand that I can't fix it.
Can you help me please?

here is the command:
`$fanc pca -Z -p /media/pca_hic_fanc_SMC1_reps.pca.png SMC1_n1.allValidPairs.hic@1000000 SMC_n2.allValidPairs.hic@1000000 pca_hic_fanc_RAD21_reps.pca`

```
2020-06-27 23:26:41,147 INFO Calculating scaling factor...
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
X
Y
M
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
X
Y
M
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
X
Y
M
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
X
Y
M
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 2376, in pca
    scale=scale)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 599, in hic_pca
    filters=filters, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 43, in _edge_collection
    s = hic.scaling_factor(reference_hic)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 1317, in scaling_factor
    for v1 in self.edge_data(weight_column, lazy=True):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 848, in edge_data
    for edge in self.edges(*args, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 755, in __call__
    *args, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 973, in _edges_subset
    for x, y, weight in self._read_matrix(row_span, col_span):
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 872, in _read_matrix
    matrix_file_position = self._matrix_positions()[(str(chromosome1_ix), str(chromosome2_ix))]
KeyError: ('9', '25')
```

```
$ fanc --version
0.8.32
```

Thank you for your time

**Comment by kaukrise** [comment]
Hi! I just fixed a bug where an exception was raised when there are no contacts between specific chromosomes in a Juicer file. I think this will have fixed your issue - could you please upgrade to `0.8.33` and try again? Thanks!

**Comment by Rseq** [comment]
Hi!

Many thanks for the prompt reply! 
Although I received this error:
`2020-06-28 11:11:21,811 INFO Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.`
It did work for that samples. 

However it did not work using same command for different samples:

```
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 2376, in pca
    scale=scale)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 599, in hic_pca
    filters=filters, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 43, in _edge_collection
    s = hic.scaling_factor(reference_hic)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 1317, in scaling_factor
    for v1 in self.edge_data(weight_column, lazy=True):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 848, in edge_data
    for edge in self.edges(*args, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 696, in __call__
    bias = self._regions_pairs.bias_vector()
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 1037, in bias_vector
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 1037, in <listcomp>
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 734, in _region_iter
    norm = self.normalisation_vector(chromosome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 667, in normalisation_vector
    "resolution: {}, unit: {}".format(chromosome, normalisation, resolution, unit))
ValueError: Cannot find normalisation vector that matches chromosome: M, normalisation: KR, resolution: 1000000, unit: BP
```

**Comment by kaukrise** [comment]
Hi!

The font warning is system-specific, and probably related to `matplotlib`, this is not something I can fix from within FAN-C.

You are getting the other error because chromosome M has not been KR normalised (probably because it is too small). At the moment, there is no option in `pca` to exclude specific chromosomes, so you can either:

1. Run `fanc pca` with the `-r` option for a PCA on a specific region (e.g. `1`)
2. Subset the Juicer `.hic` object to remove `M` outside of FAN-C and the run `fanc pca` again

**Comment by Rseq** [comment]
Hi,
Thanks for the reply. 

I did as you suggested, but I still got the same error:

```
#removing chrM reads
$sed '/chrM/d' SMC2_N1.allValidPairs > SMC2_N1_no-chrM.allValidPairs 
$sed '/chrM/d' SMC2_N2.allValidPairs > SMC2_N2_no-chrM.allValidPairs 
#checking if it was moved
$grep "chrM" SMC2_N1_no-chrM.allValidPairs 
$grep "chrM" SMC2_N2_no-chrM.allValidPairs 
#transform to .hic
$/home/user/Tools/HiC-Pro/bin/utils/hicpro2juicebox.sh -i SMC2_N1_no-chrM.allValidPairs -g /media/user/Genomes_ref/bowtie2/Hsapiens/chrom_hg19.sizes -j /home/user/Tools/Juicer/juicer_tools_1.19.02.jar -r /media/user/Genomes_ref/bowtie2/Hsapiens/digested_ref/DpnII_resfrag_hg19.bed -o . 
$/home/user/Tools/HiC-Pro/bin/utils/hicpro2juicebox.sh -i SMC2_N2_no-chrM.allValidPairs -g /media/user/Genomes_ref/bowtie2/Hsapiens/chrom_hg19.sizes -j /home/user/Tools/Juicer/juicer_tools_1.19.02.jar -r /media/user/Genomes_ref/bowtie2/Hsapiens/digested_ref/DpnII_resfrag_hg19.bed -o . 
$ fanc pca -Z -p pca_hic_fan_1M_SMC2_reps.png SMC2_N1_no-chrM.allValidPairs.hic@100000 SMC2_N1_no-chrM.allValidPairs.hic@100000 pca_hic_fanc_1M_SMC2_reps
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
X
Y
M
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 2376, in pca
    scale=scale)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 599, in hic_pca
    filters=filters, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 43, in _edge_collection
    s = hic.scaling_factor(reference_hic)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 1317, in scaling_factor
    for v1 in self.edge_data(weight_column, lazy=True):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 848, in edge_data
    for edge in self.edges(*args, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 696, in __call__
    bias = self._regions_pairs.bias_vector()
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 1037, in bias_vector
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 1037, in <listcomp>
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 734, in _region_iter
    norm = self.normalisation_vector(chromosome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 667, in normalisation_vector
    "resolution: {}, unit: {}".format(chromosome, normalisation, resolution, unit))
ValueError: Cannot find normalisation vector that matches chromosome: M, normalisation: KR, resolution: 100000, unit: BP

```

Adding -r option with chr1 or chr2 or 1 or 2 gave me the same ouput:

```
$ fanc pca -r chr1 -Z -p pca_hic_fan_1M_SMC2_reps.png SMC2_N1_no-chrM.allValidPairs.hic@100000 SMC2_N1_no-chrM.allValidPairs.hic@100000 pca_hic_fanc_1M_SMC2_reps
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
X
Y
M
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 2376, in pca
    scale=scale)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 599, in hic_pca
    filters=filters, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 43, in _edge_collection
    s = hic.scaling_factor(reference_hic)
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 1317, in scaling_factor
    for v1 in self.edge_data(weight_column, lazy=True):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 848, in edge_data
    for edge in self.edges(*args, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 696, in __call__
    bias = self._regions_pairs.bias_vector()
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 1037, in bias_vector
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 1037, in <listcomp>
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 734, in _region_iter
    norm = self.normalisation_vector(chromosome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 667, in normalisation_vector
    "resolution: {}, unit: {}".format(chromosome, normalisation, resolution, unit))
ValueError: Cannot find normalisation vector that matches chromosome: M, normalisation: KR, resolution: 100000, unit: BP

```

Any ideas what can be?
thanks

**Comment by kaukrise** [comment]
Yes, this was a bug. I think I have fixed it in the latest version (`0.8.34`), could you give it a go, please? There should be a warning, but it should no longer crash. Thank you!

**Comment by kaukrise** [comment]
Also, I have added support for multiple regions with `fanc pca`, so you can now do

```bash
fanc pca -r chr1,chr2,chr3,chr4  # note multiple regions here \
  -Z -p pca_hic_fan_1M_SMC2_reps.png SMC2_N1_no-chrM.allValidPairs.hic@100000 \
  SMC2_N2_no-chrM.allValidPairs.hic@100000 pca_hic_fanc_1M_SMC2_reps
```

This allows you to exclude any chromosomes that might give trouble in the future.

**Comment by Rseq** [comment]
Although looks fine, it can be some issue with the file itself..

```
$ fanc pca -r chr3,chr4 -Z -p pca_hic_fan_1M_SMC2_reps.png SMC2_N1_no-chrM.allValidPairs.hic@100000 SMC2_N2_no-chrM.allValidPairs.hic@100000 pca_hic_fanc_1M_SMC2_reps

2020-07-01 10:41:36,605 INFO Calculating scaling factor...
/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py:739: UserWarning: Cannot find bias vector (KR, 100000 resolution) for chromosome M.Continuing by masking the corresponding regions. If this is unexpected, try choosing another normalisation method!
  self._resolution, chromosome))

Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 124, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 90, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 2376, in pca
    scale=scale)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 624, in hic_pca
    filters=filters, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fanc/architecture/comparisons.py", line 77, in _edge_collection
    for edge in hic.edges(region_pair, lazy=True, **kwargs):
  File "/usr/local/lib/python3.6/dist-packages/fanc/matrix.py", line 718, in __call__
    for r in row_regions:
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 763, in _region_subset
    subset_ix, subset_start = self._region_start(region)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 716, in _region_start
    offset_ix = self._chromosome_ix_offset(region.chromosome)
  File "/usr/local/lib/python3.6/dist-packages/fanc/compatibility/juicer.py", line 699, in _chromosome_ix_offset
    raise ValueError("Chromosome {} not in matrix.".format(target_chromosome))
ValueError: Chromosome chr3 not in matrix.

```

Same error independent of which -r region I pick

**Comment by kaukrise** [comment]
Since this is Juicer, have you tried `-r 1,2,3`?

**Comment by Rseq** [comment]
True, I forgot about this detail 
Working well now! 
Many thanks!
