### ISSUE TITLE
ERROR plotting a line plot

### ISSUE THREAD

**Issue by Gonysh** [vaquerizaslab/fanc#49]
Hello dear FAN-C team,

I tried using fancplot CLI to plot a panel and a line plot using a .hic file and a bigwig file.
Plotting multipanel plots with refseq tracks went fine.

Trying to plot a single line plot for the same coordinates, using a bigwig file from the ENCODE project gave the following output:

>>> fancplot 17:40465000-40665000 -o test.png -p line ENCFF965VYA_GM12878_minus_strand_unique_reads.bw
2021-03-18 14:04:16,665 INFO Using non-interactive backend
[E::hts_hopen] Failed to open file ENCFF965VYA_GM12878_minus_strand_unique_reads.bw
[E::hts_open_format] Failed to open file "ENCFF965VYA_GM12878_minus_strand_unique_reads.bw" : Exec format error
2021-03-18 14:04:17,423 INFO Found 1 regions
/specific/elkon/gonyshanel/python37/bin/fancplot:164: UserWarning: There was an error with plot 0, region 17:40465000-40665000 (Traceback (most recent call last):
  File "/specific/elkon/gonyshanel/python37/bin/fancplot", line 144, in __init__
    fig, axes = gf.plot(plot_region)
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/base_plotter.py", line 292, in plot
    plot_output = self._plot(region)
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/plotter.py", line 984, in _plot
    for i, x, y in self._line_values(region):
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/plotter.py", line 978, in _line_values
    x, y = self.values_from_region_iter(region_iter, self.attribute)
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/base_plotter.py", line 523, in values_from_region_iter
    return self._STYLES[self.style](self, regions, attribute)
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/base_plotter.py", line 510, in _get_values_per_mid
    for region in regions:
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/fanc/plotting/plotter.py", line 926, in _region_iter
    for region in data.regions(region, **kwargs):
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/genomic_regions/regions.py", line 1675, in _region_subset
    for start, end, score in self.region_intervals(r):
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/genomic_regions/regions.py", line 956, in region_intervals
    raw_intervals = self._region_intervals(region, score_field=score_field, *args, **kwargs)
  File "/specific/elkon/gonyshanel/python37/lib/python3.7/site-packages/genomic_regions/regions.py", line 1687, in _region_intervals
    intervals = self.bw.intervals(region.chromosome, region.start, region.end)
RuntimeError: Invalid interval bounds!
)
  tb))
2021-03-18 14:04:17,451 WARNING Invalid interval bounds!

**Comment by kaukrise** [comment]
The ENCODE file you posted uses `chr` prefixes.

```
fancplot chr17:40465000-40665000 -o test.png -p line ENCFF965VYA_GM12878_minus_strand_unique_reads.bw
```

![test](https://user-images.githubusercontent.com/1540112/111647033-6e7e1180-8802-11eb-93ba-1f1ebedad17c.png)

**Comment by Gonysh** [comment]
Thank you for the quick reply.

Your solution worked.

(Although I'm still getting an error output alongside the production of the plot):
>>>2021-03-18 18:37:00,941 INFO Using non-interactive backend
[E::hts_hopen] Failed to open file ENCFF965VYA_GM12878_minus_strand_unique_reads.bw
[E::hts_open_format] Failed to open file "ENCFF965VYA_GM12878_minus_strand_unique_reads.bw" : Exec format error
2021-03-18 18:37:12,023 INFO Found 1 regions

**Comment by kaukrise** [comment]
Hey, the error you are seeing can safely be ignored. I am working on a way to quench the message in the future

**Comment by kaukrise** [comment]
Just as an update, if you install the `genomic_regions` package version `0.0.10` the error message will be gone.
