### ISSUE TITLE
TypeError raised when calling fanc.architecture.compartments.ABCompartmentMatrix.from_hic with oe_per_chromosome=False

### ISSUE THREAD

**Issue by srcoulombe** [vaquerizaslab/fanc#50]
Python version: 3.7.10
fanc version: 0.9.0

Downloaded the .hic file from [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE82144)

Reproducing code:
```
>>> hic_fp=r"GSE82144_Kieffer-Kwon-2017-resting_B_cells_WT_30.hic"
>>> hic = fanc.load(hic_fp+"@50000")
>>> ab = fanc.architecture.compartments.ABCompartmentMatrix.from_hic(hic, oe_per_chromosome=False)

/home/scoulom8/miniconda3/envs/my_fanc_env/lib/python3.7/site-packages/fanc/compatibility/juicer.py:604: RuntimeWarning: divide by zero encountered in true_divide
  return np.array(vectors[resolution]) / sf

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scoulom8/miniconda3/envs/my_fanc_env/lib/python3.7/site-packages/fanc/architecture/compartments.py", line 105, in from_hic
    m = hic.matrix((chromosome, chromosome), oe=True, oe_per_chromosome=oe_per_chromosome)
  File "/home/scoulom8/miniconda3/envs/my_fanc_env/lib/python3.7/site-packages/fanc/matrix.py", line 1024, in matrix
    for source, sink, weight in matrix_entries:
  File "/home/scoulom8/miniconda3/envs/my_fanc_env/lib/python3.7/site-packages/fanc/matrix.py", line 984, in <genexpr>
    entry_iter = ((i, j, weight)
  File "/home/scoulom8/miniconda3/envs/my_fanc_env/lib/python3.7/site-packages/fanc/matrix.py", line 970, in offset_iter
    for edge in edge_iter:
  File "/home/scoulom8/miniconda3/envs/my_fanc_env/lib/python3.7/site-packages/fanc/matrix.py", line 760, in __call__
    edge.expected = ex[abs(sink - source)]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by kaukrise** [comment]
Hi, thanks for the report.

Juicer files only store per-chromosome expected values, so `oe_per_chromosome=False` is not supported. In general, we would strongly recommend keeping `oe_per_chromosome=True`. Hi-C files will typically be corrected independently for each chromosome, and also calculate expected values accordingly. Setting `oe_per_chromosome=False` when you are not controlling the matrix generation process can strongly bias your results.

I will add a more descriptive warning message to the next version.

**Comment by srcoulombe** [comment]
Got it, thanks for the reply!
