### ISSUE TITLE
example produces "builtin cmap 'viridis'" error

### ISSUE THREAD

**Issue by GodloveD** [vaquerizaslab/fanc#51]
I'm trying to work through the example [here](https://fan-c.readthedocs.io/en/latest/getting_started.html#example-analysis) with version 0.9.15 installed via `pip`.  I keep getting the following error.  Am I doing something wrong?  Thanks!

```
$ fanc auto SRR4271982_chr18_19_1.fastq.gzip SRR4271982_chr18_19_2.fastq.gzip output/ \
>           -g hg19_chr18_19.fa -i hg19_chr18_19/hg19_chr18_19 -n fanc_example -t 4 -r HindIII \
>           --split-ligation-junction -q 30 --run-with test
2021-03-29 15:30:38,351 INFO FAN-C version: 0.9.15
2021-03-29 15:30:38,353 INFO Output folder: output/
2021-03-29 15:30:38,353 INFO Input files: SRR4271982_chr18_19_1.fastq.gzip, SRR4271982_chr18_19_2.fastq.gzip
2021-03-29 15:30:38,354 INFO Input file types: fastq, fastq
2021-03-29 15:30:38,354 INFO Final basename: fanc_example (you can change this with the -n option!)
0 (threads: 4, depends on: ): fanc map -m 25 -s 3 -t 4 --no-iterative --restriction-enzyme HindIII SRR4271982_chr18_19_1.fastq.gzip hg19_chr18_19/hg19_chr18_19 output/sam/SRR4271982_chr18_19_1.bam
1 (threads: 4, depends on: ): fanc map -m 25 -s 3 -t 4 --no-iterative --restriction-enzyme HindIII SRR4271982_chr18_19_2.fastq.gzip hg19_chr18_19/hg19_chr18_19 output/sam/SRR4271982_chr18_19_2.bam
2 (threads: 1, depends on: 0, 1): fanc sort_sam -t 4 output/sam/SRR4271982_chr18_19_1.bam
3 (threads: 1, depends on: 0, 1): fanc sort_sam -t 4 output/sam/SRR4271982_chr18_19_2.bam
4 (threads: 4, depends on: 2, 3): fanc pairs -f -g hg19_chr18_19.fa -t 4 -us -r HindIII -q 30.0 -S output/sam/SRR4271982_chr18_19_1.bam output/sam/SRR4271982_chr18_19_2.bam output/pairs/fanc_example.pairs
5 (threads: 1, depends on: 4): fanc pairs -d 10000 -l -p 2 --statistics-plot output/plots/stats/fanc_example.pairs.stats.pdf output/pairs/fanc_example.pairs
6 (threads: 1, depends on: 5): fanc pairs --ligation-error-plot output/plots/stats/fanc_example.pairs.ligation_error.pdf output/pairs/fanc_example.pairs
7 (threads: 1, depends on: 5): fanc pairs --re-dist-plot output/plots/stats/fanc_example.pairs.re_dist.pdf output/pairs/fanc_example.pairs
8 (threads: 1, depends on: 5): fanc hic -f output/pairs/fanc_example.pairs output/hic/fanc_example.hic
9 (threads: 4, depends on: 8): fanc hic -f -b 5000000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_5mb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_5mb.hic
10 (threads: 4, depends on: 8): fanc hic -f -b 2000000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_2mb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_2mb.hic
11 (threads: 4, depends on: 8): fanc hic -f -b 1000000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_1mb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_1mb.hic
12 (threads: 4, depends on: 8): fanc hic -f -b 500000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_500kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_500kb.hic
13 (threads: 4, depends on: 8): fanc hic -f -b 250000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_250kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_250kb.hic
14 (threads: 4, depends on: 8): fanc hic -f -b 100000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_100kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_100kb.hic
15 (threads: 4, depends on: 8): fanc hic -f -b 50000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_50kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_50kb.hic
16 (threads: 4, depends on: 8): fanc hic -f -b 25000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_25kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_25kb.hic
17 (threads: 4, depends on: 8): fanc hic -f -b 10000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_10kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_10kb.hic
18 (threads: 4, depends on: 8): fanc hic -f -b 5000 -r 0.1 -t 4 --statistics-plot output/plots/stats/fanc_example_5kb.stats.pdf -n --norm-method kr output/hic/fanc_example.hic output/hic/binned/fanc_example_5kb.hic
Singularity> fanc auto SRR4271982_chr18_19_1.fastq.gzip SRR4271982_chr18_19_2.fastq.gzip output/           -g hg19_chr18_19.fa -i hg19_chr18_19/hg19_chr18_19 -n fanc_example -t 4 -r HindIII           --split-ligation-junction -q 30
2021-03-29 15:30:54,988 INFO FAN-C version: 0.9.15
2021-03-29 15:30:54,991 INFO Output folder: output/
2021-03-29 15:30:54,991 INFO Input files: SRR4271982_chr18_19_1.fastq.gzip, SRR4271982_chr18_19_2.fastq.gzip
2021-03-29 15:30:54,991 INFO Input file types: fastq, fastq
2021-03-29 15:30:54,991 INFO Final basename: fanc_example (you can change this with the -n option!)
2021-03-29 15:30:54,991 INFO Creating output folders...
2021-03-29 15:30:56,425 INFO FAN-C version: 0.9.15
2021-03-29 15:30:56,427 INFO Starting mapping for SRR4271982_chr18_19_1.fastq.gzip
2021-03-29 15:30:56,492 INFO Starting to output alignments to intermediate SAM file /tmp/tmpj0wow_5h/intermediate.sam
2021-03-29 15:33:56,809 INFO Converting intermediate SAM file to BAM (output/sam/SRR4271982_chr18_19_1.bam)
2021-03-29 15:34:22,207 INFO Success, removing intermediate.
2021-03-29 15:34:24,041 INFO FAN-C version: 0.9.15
2021-03-29 15:34:24,043 INFO Starting mapping for SRR4271982_chr18_19_2.fastq.gzip
2021-03-29 15:34:24,103 INFO Starting to output alignments to intermediate SAM file /tmp/tmpvly3ik60/intermediate.sam
2021-03-29 15:37:24,126 INFO Converting intermediate SAM file to BAM (output/sam/SRR4271982_chr18_19_2.bam)
2021-03-29 15:37:48,878 INFO Success, removing intermediate.
2021-03-29 15:37:50,728 INFO FAN-C version: 0.9.15
2021-03-29 15:37:50,730 INFO Cannot find sambamba on this machine, falling back to samtools sort. This is not a problem, but if you want to speed up your SAM/BAM file sorting, install sambamba and ensure it is in your PATH!
2021-03-29 15:37:50,739 INFO FAN-C version: 0.9.15
2021-03-29 15:37:50,740 INFO Cannot find sambamba on this machine, falling back to samtools sort. This is not a problem, but if you want to speed up your SAM/BAM file sorting, install sambamba and ensure it is in your PATH!
2021-03-29 15:38:21,800 INFO Replacing input SAM/BAM file output/sam/SRR4271982_chr18_19_2.bam with sorted version...
2021-03-29 15:38:22,976 INFO Replacing input SAM/BAM file output/sam/SRR4271982_chr18_19_1.bam with sorted version...
2021-03-29 15:38:27,006 INFO FAN-C version: 0.9.15
2021-03-29 15:38:27,007 INFO Getting genome regions (fragments or bins)
2021-03-29 15:38:27,007 INFO Getting regions
2021-03-29 15:38:36,876 INFO Three arguments detected, assuming SAM/BAM input.
[E::idx_find_and_load] Could not retrieve index file for 'output/sam/SRR4271982_chr18_19_1.bam'
2021-03-29 15:38:36,878 INFO Using filters appropriate for Bowtie2.
[E::idx_find_and_load] Could not retrieve index file for 'output/sam/SRR4271982_chr18_19_1.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/sam/SRR4271982_chr18_19_2.bam'
Buffers 100% (630 of 630) |##################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2021-03-29 15:39:55,093 INFO Updating region mappability
Mappability 100% (1612198 of 1612198) |######################################| Elapsed Time: 0:00:10 Time:  0:00:10
2021-03-29 15:40:13,234 INFO All done.
Closing remaining open files:8L87S8...done
2021-03-29 15:40:14,952 INFO FAN-C version: 0.9.15
2021-03-29 15:40:14,954 INFO One argument received, assuming existing Pairs object.
2021-03-29 15:40:14,984 INFO Filtering reads with RE distance > 10000bp
2021-03-29 15:40:14,984 INFO Filtering self-ligated read pairs
2021-03-29 15:40:14,985 INFO Filtering PCR duplicates, threshold <= 2bp
2021-03-29 15:40:25,784 INFO PCR duplicate stats: 186071 (11.5%) of pairs marked as duplicate.  (multiplicity:occurances) 3:15319 2:149415 4:1520 5:206 10:6 12:2 6:43 7:20 8:6 9:4 14:2
2021-03-29 15:40:25,784 INFO Running filters...
Filter 100% (630 of 630) |###################################################| Elapsed Time: 0:00:36 Time:  0:00:36
2021-03-29 15:41:09,994 INFO Total: 1612198. Valid: 666177
2021-03-29 15:41:09,994 INFO Updating region mappability
Mappability 100% (666177 of 666177) |########################################| Elapsed Time: 0:00:08 Time:  0:00:08
2021-03-29 15:41:26,919 INFO Done.
2021-03-29 15:41:27,919 INFO generated new fontManager
2021-03-29 15:41:43,637 INFO Saving statistics...
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 127, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.8/dist-packages/fanc/commands/fanc_commands.py", line 1071, in pairs
    from fanc.plotting.statistics import summary_statistics_plot
  File "/usr/local/lib/python3.8/dist-packages/fanc/plotting/__init__.py", line 226, in <module>
    plt.register_cmap(name='viridis', cmap=viridis)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/cm.py", line 149, in register_cmap
    raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'viridis'.
Closing remaining open files:output/pairs/fanc_example.pairs...done
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 127, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.8/dist-packages/fanc/commands/fanc_commands.py", line 115, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fanc/commands/auto.py", line 1290, in auto
    runner.run()
  File "/usr/local/lib/python3.8/dist-packages/fanc/commands/auto.py", line 141, in run
    raise RuntimeError("Task {} had non-zero exit status. "
RuntimeError: Task 32ffbe6c-b346-4f4e-9fad-f45d46bd12aa had non-zero exit status. Cancelling execution of all tasks.
```

**Comment by kaukrise** [comment]
Hi, thanks a lot for reporting this, you are doing everything correctly.

We wrote the FAN-C plotting API before the new, perceptually uniform colormaps became the default in Matplotlib (the plotting library FAN-C depends on). But we liked them a lot, so we included them manually. This hasn't been an issue previously, but it looks like Matplotlib is now complaining that these already exist.

It was just a matter of removing the manual colormap addition, which is no longer necessary in any case. You can update to `0.9.16`, which should now be available, and everything should work again as expected. Let me know if you run into any further issues!

```
pip install --upgrade fanc
```

**Comment by GodloveD** [comment]
Works now.  Thanks for the quick response!

**Comment by baishengjun** [comment]
Hi，
When I running the example data, it shows the error `[E::idx_find_and_load] Could not retrieve index file for 'output/sam/SRR4271982_chr18_19_1.bam'  `,but it still works. Does the error message affect the final results?
