### ISSUE TITLE
cancelling execution of all tasks

### ISSUE THREAD

**Issue by gorliver** [vaquerizaslab/fanc#54]
I'm trying to run fanc using the example data and have the following errors ( the command is the same as in the turorial document):
```
2021-04-26 16:04:52,355 INFO FAN-C version: 0.9.17
2021-04-26 16:04:52,358 INFO Output folder: output/
2021-04-26 16:04:52,358 INFO Input files: SRR4271982_chr18_19_1.fastq.gzip, SRR4271982_chr18_19_2.fastq.gzip
2021-04-26 16:04:52,358 INFO Input file types: fastq, fastq
2021-04-26 16:04:52,358 INFO Final basename: fanc_example_bowtie2 (you can change this with the -n option!)
2021-04-26 16:04:52,358 INFO Creating output folders...
2021-04-26 16:04:54,902 INFO FAN-C version: 0.9.17
2021-04-26 16:04:54,904 INFO Starting mapping for SRR4271982_chr18_19_1.fastq.gzip
2021-04-26 16:04:54,965 INFO Starting to output alignments to intermediate SAM file /tmp/tmpnmsmrete/intermediate.sam
2021-04-26 16:07:14,335 INFO Converting intermediate SAM file to BAM (output/sam/SRR4271982_chr18_19_1.bam)
2021-04-26 16:07:45,182 INFO Success, removing intermediate.
2021-04-26 16:07:47,845 INFO FAN-C version: 0.9.17
2021-04-26 16:07:47,847 INFO Starting mapping for SRR4271982_chr18_19_2.fastq.gzip
2021-04-26 16:07:47,905 INFO Starting to output alignments to intermediate SAM file /tmp/tmpnfax1z5i/intermediate.sam
2021-04-26 16:10:05,348 INFO Converting intermediate SAM file to BAM (output/sam/SRR4271982_chr18_19_2.bam)
2021-04-26 16:10:35,662 INFO Success, removing intermediate.
2021-04-26 16:10:38,342 INFO FAN-C version: 0.9.17
2021-04-26 16:10:38,344 INFO Cannot find sambamba on this machine, falling back to samtools sort. This is not a problem, but if you want to speed up your SAM/BAM file sorting, install sambamba and ensure it is in your PATH!
2021-04-26 16:10:38,519 INFO FAN-C version: 0.9.17
2021-04-26 16:10:38,521 INFO Cannot find sambamba on this machine, falling back to samtools sort. This is not a problem, but if you want to speed up your SAM/BAM file sorting, install sambamba and ensure it is in your PATH!
2021-04-26 16:11:13,059 INFO Replacing input SAM/BAM file output/sam/SRR4271982_chr18_19_1.bam with sorted version...
2021-04-26 16:11:13,579 INFO Replacing input SAM/BAM file output/sam/SRR4271982_chr18_19_2.bam with sorted version...
2021-04-26 16:11:16,326 INFO FAN-C version: 0.9.17
2021-04-26 16:11:16,327 INFO Getting genome regions (fragments or bins)
2021-04-26 16:11:16,327 INFO Getting regions
2021-04-26 16:11:27,593 INFO Three arguments detected, assuming SAM/BAM input.
2021-04-26 16:11:27,594 INFO Using filters appropriate for Bowtie2.
Traceback (most recent call last):
  File "/home/hnzhao/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/hnzhao/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 962, in pairs
    batch_size=batch_size)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/pairs.py", line 126, in generate_pairs_split
    read_filters=read_filters, check_sorted=check_sorted)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/pairs.py", line 1474, in add_read_pairs_from_sam
    self.flush()
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/pairs.py", line 1238, in flush
    RegionPairsTable.flush(self, silent=silent)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/matrix.py", line 1705, in flush
    self._flush_edges(silent=silent, update_mappability=update_mappability)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/matrix.py", line 1684, in _flush_edges
    self._edge_buffer.flush()
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/matrix.py", line 1433, in flush
    prefix="Buffers") as pb:
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/tools/general.py", line 461, in __init__
    poll_interval=poll_interval, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'min_value'
Closing remaining open files:9855U7...doneoutput/pairs/fanc_example_bowtie2.pairs...done
Traceback (most recent call last):
  File "/home/hnzhao/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/hnzhao/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 115, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/auto.py", line 1290, in auto
    runner.run()
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/auto.py", line 142, in run
    "Cancelling execution of all tasks.".format(task.id))
RuntimeError: Task 09b72089-73e2-412d-9a08-975c9c67c24b had non-zero exit status. Cancelling execution of all tasks.

```
I also tried the BWA index and get the following errors:
```
2021-04-26 15:55:11,660 INFO FAN-C version: 0.9.17
2021-04-26 15:55:11,663 INFO Output folder: output/
2021-04-26 15:55:11,663 INFO Input files: SRR4271982_chr18_19_1.fastq.gzip, SRR4271982_chr18_19_2.fastq.gzip
2021-04-26 15:55:11,663 INFO Input file types: fastq, fastq
2021-04-26 15:55:11,663 INFO Final basename: fanc_example_bowtie2 (you can change this with the -n option!)
2021-04-26 15:55:11,663 INFO Creating output folders...
2021-04-26 15:55:13,862 INFO FAN-C version: 0.9.17
2021-04-26 15:55:13,864 INFO Starting mapping for SRR4271982_chr18_19_1.fastq.gzip
2021-04-26 15:55:13,915 INFO Starting to output alignments to intermediate SAM file /tmp/tmpoo6gng75/intermediate.sam
Traceback (most recent call last):
  File "/home/hnzhao/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/hnzhao/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 404, in map
    trim_front=trim_front, restriction_enzyme=restriction_enzyme)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/map.py", line 973, in iterative_mapping
    raise Exception(exc)
Exception: Traceback (most recent call last):
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/map.py", line 644, in _iterative_mapping_worker
    sam_file, unmapped_file = mapper.map(input_file, output_folder=output_folder)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/map.py", line 218, in map
    raise RuntimeError('Mapping had non-zero exit status {}. {}'.format(ret, error_message))
RuntimeError: Mapping had non-zero exit status 1. mem: invalid option -- 'o'


Traceback (most recent call last):
  File "/home/hnzhao/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/hnzhao/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 115, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/auto.py", line 1290, in auto
    runner.run()
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/auto.py", line 142, in run
    "Cancelling execution of all tasks.".format(task.id))
RuntimeError: Task ed996e8f-d183-4946-801c-4e9a6c5d5096 had non-zero exit status. Cancelling execution of all tasks.
```
fanc version is 0.9.17 and python version is 3.6.5.

**Comment by kaukrise** [comment]
Hi,

regarding the first issue you are likely using the wrong or an old progressbar version. Can you please try upgrading like this?

```
pip install --upgrade progressbar2
```

You may have to uninstall `progressbar` first.

The second error stems from an old BWA version. Please upgrade BWA (I am running `0.7.17-r1188`, for example.

**Comment by gorliver** [comment]
Thank you very much!
It works perfectly!

**Comment by kaukrise** [comment]
Awesome, thanks for reporting back!
