### ISSUE TITLE
cannot perform merge

### ISSUE THREAD

**Issue by gorliver** [vaquerizaslab/fanc#55]
Hi kaukrise,
I was merging pairs from different samples into a merged fragment level matrix and get following message:
```
2021-05-03 22:41:18,976 INFO FAN-C version: 0.9.17
2021-05-03 22:41:19,485 INFO Converting Pairs files
2021-05-03 22:41:19,537 INFO Converting GSE132415/output/pairs/SRR9164344.pairs to Hic
Hi-C convert 100% (15458110 of 15458110) |##########################################################################################| Elapsed Time: 0:04:13 Time:  0:04:13
2021-05-03 22:47:05,213 INFO Converting GSE132415/output/pairs/SRR9164345.pairs to Hic
Hi-C convert 100% (38755904 of 38755904) |##########################################################################################| Elapsed Time: 0:06:56 Time:  0:06:56
2021-05-03 22:55:37,216 INFO Converting SRP040251/output/pairs/SRR1197490.pairs to Hic
Hi-C convert 100% (28471789 of 28471789) |##########################################################################################| Elapsed Time: 0:05:14 Time:  0:05:14
2021-05-03 23:02:22,424 INFO Converting SRP043612/output/pairs/SRR1504819.pairs to Hic
Hi-C convert 100% (79898917 of 79898917) |##########################################################################################| Elapsed Time: 0:13:32 Time:  0:13:32
2021-05-03 23:17:42,347 INFO Converting SRP064711/output/pairs/SRR2626163.pairs to Hic
Hi-C convert 100% (31016267 of 31016267) |##########################################################################################| Elapsed Time: 0:07:53 Time:  0:07:53
2021-05-03 23:28:51,077 INFO Converting SRP064711/output/pairs/SRR2626429.pairs to Hic
Hi-C convert 100% (37933573 of 37933573) |##########################################################################################| Elapsed Time: 0:08:27 Time:  0:08:27
2021-05-03 23:40:36,271 INFO Converting SRP095993/output/pairs/SRR5155149.pairs to Hic
Hi-C convert 100% (4996917 of 4996917) |############################################################################################| Elapsed Time: 0:05:05 Time:  0:05:05
2021-05-03 23:49:04,688 INFO Converting SRP095993/output/pairs/SRR5155151.pairs to Hic
Hi-C convert 100% (7510368 of 7510368) |############################################################################################| Elapsed Time: 0:05:18 Time:  0:05:18
2021-05-03 23:57:44,042 INFO Converting SRP224678/output/pairs/SRR10241461.pairs to Hic
Hi-C convert 100% (62493559 of 62493559) |##########################################################################################| Elapsed Time: 0:08:32 Time:  0:08:32
2021-05-04 00:06:54,165 INFO Converting SRP224678/output/pairs/SRR10241462.pairs to Hic
Hi-C convert 100% (83933244 of 83933244) |##########################################################################################| Elapsed Time: 0:10:20 Time:  0:10:20

2021-05-04 00:17:51,114 INFO Merging 10 Hic files into merged/output/hic/merged_fragment_level.hic
2021-05-04 00:17:51,455 INFO Checking if regions are identical
Traceback (most recent call last):
  File "/home/hnzhao/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/hnzhao/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 1456, in hic
    merged_hic = fanc.Hic.merge(hics, file_name=merged_hic_file, mode='w')
  File "/home/hnzhao/.local/lib/python3.6/site-packages/fanc/matrix.py", line 2542, in merge
    raise ValueError("Regions in matrix objects are not identical, "
ValueError: Regions in matrix objects are not identical, cannot perform merge!
```

The command I use is:
```
fanc hic GSE132415/output/pairs/SRR9164344.pairs GSE132415/output/pairs/SRR9164345.pairs SRP040251/output/pairs/SRR119
7490.pairs SRP043612/output/pairs/SRR1504819.pairs SRP064711/output/pairs/SRR2626163.pairs SRP064711/output/pairs/SRR2626429.pairs SRP095993/output/pairs/SRR5155149.pairs
SRP095993/output/pairs/SRR5155151.pairs SRP224678/output/pairs/SRR10241461.pairs SRP224678/output/pairs/SRR10241462.pairs merged/output/hic/merged_fragment_level.hic
```
One thing that is not identical to the samples is the enzyme. Does fanc require sample enzyme for all the samples or did I missed something?
Thank you!

Gorliver

**Comment by kaukrise** [comment]
Hi, as the message `ValueError: Regions in matrix objects are not identical, cannot perform merge!` suggests, FAN-C can only merge matrices when they are based on the same regions/binning. Different enzymes = different fragments = different bins. 

Merging objects with different binning causes a lot of problems that can likely not be resolved unambiguously. A selection of problems would be: for two overlapping bins, what would the new bins look like? Would they be merged into one larger bin? What if that overlaps yet another bin? Should the overlap become a separate bin? How do you assign contacts in either case?

With more than one object this becomes even more complicated, and the order of merging would also have to be taken into account. These are all reasons why this functionality does not exist in FAN-C.

You could bin the matrices first (`fanc hic -b <resolution>`) and merge the binned samples. Provided they are based on the same genome, this should work. However, please be aware that different enzymes may introduce different biases into the matrix, and normalisation of the merged matrix might have unintended consequences, too.

**Comment by gorliver** [comment]
Thank you for your explanation, that makes perfect sense to me now.
