### ISSUE TITLE
how to output valid reads in BAM format or equivalent?

### ISSUE THREAD

**Issue by cooketho** [vaquerizaslab/fanc#68]
I'm using SALSA to scaffold a genome assembly using Hi-C data, which requires the data to be in BED format (generated from a BAM file using bedtools bamtobed). I've used fanc to map the reads, but is there an easy way to generate a BAM file of valid Hi-C reads from the fanc output? I see there is a helper tool to dump the hic matrix to a text file, but that is not really what I want. I want the filtered reads themselves; not the fragment interaction counts. I tried following some examples in the API documentation to do this myself, but ran into errors. So I guess my other question is: am I doing something wrong? Thank you!

```
import fanc
from fanc.pairs import SelfLigationFilter
pairs = fanc.load('test/pairs/hm_hic.pairs')
sl_filter = SelfLigationFilter(mask='self-ligation')
pairs.filter(sl_filter)
for pair in pairs.pairs(excluded_filters=['self-ligation']):
    print(pair)
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lib/python3.6/site-packages/fanc/pairs.py", line 1915, in pairs
    for row in self.edges_dict(key=key, *args, **kwargs):
  File "/home/lib/python3.6/site-packages/fanc/matrix.py", line 1909, in _edge_subset_rows_from_regions
    maskable=self):
  File "/home/lib/python3.6/site-packages/fanc/general.py", line 707, in iterrows
    return MaskedTableView(self, it, excluded_masks=excluded_filters, maskable=maskable)
  File "/home/lib/python3.6/site-packages/fanc/general.py", line 569, in __init__
    self.excluded_mask_ix = maskable.get_binary_mask_from_masks(excluded_masks)
  File "/home/lib/python3.6/site-packages/fanc/general.py", line 456, in get_binary_mask_from_masks
    o.append(2**self.get_mask(m).ix)
AttributeError: 'KeyError' object has no attribute 'ix'

**Comment by kaukrise** [comment]
Hi, you've stumbled on an unrelated error (or so it seems), but you cannot use the `pairs` object to generate BAM reads that way in any case.

Generating valid pairs BAM files is not something FAN-C was designed to do - other tools like HiC-Pro are much more suitable for that purpose. The pairs object is useful in other ways, but it does not save all the BAM information after the initial BAM loading step for efficiency, I'm afraid.
