### ISSUE TITLE
Give some meaningful error message in fancplot split when using different resolutions

### ISSUE THREAD

**Issue by balwierz** [vaquerizaslab/fanc#7]
Hi I tried fancplot split and chose two different binning resolutions.
Right now it looks like this:
```
2020-02-11 13:42:48,741 INFO Found 1 regions
qt5ct: using qt5ct plugin
/usr/local/bin/fancplot:157: UserWarning: There was an error with plot 0, region chr1:14000000-20000000 (Traceback (most recent call last):
  File "/usr/local/bin/fancplot", line 139, in __init__
    fig, axes = gf.plot(plot_region)
  File "/usr/local/lib/python3.7/dist-packages/fanc/plotting/plotter.py", line 211, in plot
    p.plot(r)
  File "/usr/local/lib/python3.7/dist-packages/fanc/plotting/base_plotter.py", line 785, in plot
    plot_output = self._plot((x_region, y_region))
  File "/usr/local/lib/python3.7/dist-packages/fanc/plotting/hic_plotter.py", line 296, in _plot
    self._refresh(region)
  File "/usr/local/lib/python3.7/dist-packages/fanc/plotting/hic_plotter.py", line 339, in _refresh
    self.current_matrix = self.hic_buffer.get_matrix(*region)
  File "/usr/local/lib/python3.7/dist-packages/fanc/plotting/hic_plotter.py", line 143, in get_matrix
    self._BUFFERING_STRATEGIES[self.buffering_strategy](self, *regions)
  File "/usr/local/lib/python3.7/dist-packages/fanc/plotting/hic_plotter.py", line 186, in _buffer_relative
    norm=self.norm, oe=self.oe, log=self.log)
  File "/usr/local/lib/python3.7/dist-packages/fanc/architecture/comparisons.py", line 494, in matrix
    m_bottom[top_indices] = m_top[top_indices]
  File "/usr/local/lib/python3.7/dist-packages/fanc/matrix.py", line 2605, in __setitem__
    np.ma.MaskedArray.__setitem__(self, key, item)
  File "/usr/lib/python3/dist-packages/numpy/ma/core.py", line 3327, in __setitem__
    _data[indx] = dval
IndexError: index 73 is out of bounds for axis 0 with size 73
)
  tb))
2020-02-11 13:43:01,556 WARNING index 73 is out of bounds for axis 0 with size 73
```

**Comment by kaukrise** [comment]
Added a check for equal bin sizes in 0.8.18

**Comment by davidmasp** [comment]
Hi, I am having a similar issue (the message looks very similar), but with the `fanc loops` command.

I am using a multi-resolution file that I downloaded from the 4DN website, I was wandering what does it mean to define different resolutions and how it might lead to the issue in that command because as far as I understand there is only one way to define the resolution no?

The command looks more or less like this.

```
fanc loops 4DNFI2TK7L2F.hic@5000   microcH1_5000_loopsAnnotate.loops    -t 5  
```

and the error looks like this

````
Traceback (most recent call last):
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/gridmap/job.py", line 242, in execute
    self.ret = self.function(*self.args, **self.kwlist)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/fanc/peaks.py", line 1365, in process_matrix_segment_intra
    m_expected = expected_f(m_distance)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2192, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/fanc/peaks.py", line 1364, in <lambda>
    expected_f = np.vectorize(lambda x: e[x])
IndexError: index 49791 is out of bounds for axis 0 with size 49791
Traceback (most recent call last):
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 2881, in loops
    peaks = pk.call_peaks(matrix, chromosome_pairs=chromosome_pairs, file_name=o)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/fanc/peaks.py", line 1270, in call_peaks
    self._find_peaks_intra_matrix(m, intra_expected[chromosome1], c[start1:end1],
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/fanc/peaks.py", line 1167, in _find_peaks_intra_matrix
    self._process_jobs(jobs, peak_info, observed_chunk_distribution)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/fanc/peaks.py", line 1056, in _process_jobs
    results = msgpack.loads(compressed_results, strict_map_key=False)
  File "/home/dmas/nxf_conda_env/HiCannotation-e79c6b7076dd13ce2817d3f6422eaed6/lib/python3.8/site-packages/msgpack_numpy.py", line 273, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 178, in msgpack._cmsgpack.unpackb
  File "msgpack/_unpacker.pyx", line 126, in msgpack._cmsgpack.get_data_from_buffer
TypeError: a bytes-like object is required, not 'IndexError'
````
