### ISSUE TITLE
Fanc aggregate regions file format?

### ISSUE THREAD

**Issue by 14stutzmanav** [vaquerizaslab/fanc#71]
Hello there!

I'm trying to generate aggregate peak plots and am running into an issue where fanc aggregate does not accept the regions file I'm using as input. I was wondering what the requirements are for a regions file? I am using fanc version 0.9.14. I initially used a .narrowPeak file and it gave the following error:

```
$ fanc aggregate -m fanc-hwt-3LW-HiC-merge_2kb_k9me3-peaks-in-hwt.aggregateMatrix -p fanc-hwt-3LW-HiC-merge_2kb_k9me3-peaks-in-hwt.pdf -w 100000 ../../hp1a-cnr/k9me3_cnr/Peaks/HWT_K9me3_pel-merged_dm6_trim_q5_dupsRemoved_allFrags_peaks.narrowPeak ../fanc-hwt-3LW-HiC-merge/hic/binned/hwt-3LW-HiC-merge_2kb.hic 
2021-08-18 11:14:40,356 INFO FAN-C version: 0.9.14
Traceback (most recent call last):
  File "/nas/longleaf/home/alexisv7/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/nas/longleaf/home/alexisv7/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 4619, in aggregate
    b = matrix.bin_size
AttributeError: 'Bed' object has no attribute 'bin_size'
Closing remaining open files:../fanc-hwt-3LW-HiC-merge/hic/binned/hwt-3LW-HiC-merge_2kb.hic...done
```

I also tried generating a custom bed file that included the first four traditional bed file columns (chrom, start, end, name) and a fifth column titled bin_size that was calculated by subtracting start from stop coordinates. When I use this file (that has a header with each of the column names), here's the output:
```
$ fanc aggregate -m fanc-hwt-3LW-HiC-merge_2kb_k9me3-peaks-in-hwt.aggregateMatrix -p fanc-hwt-3LW-HiC-merge_2kb_k9me3-peaks-in-hwt.pdf -w 100000 HWT_K9me3_pel-merged_dm6_trim_q5_dupsRemoved_allFrags_peaks-with-width.bed ../fanc-hwt-3LW-HiC-merge/hic/binned/hwt-3LW-HiC-merge_2kb.hic 
2021-08-18 11:17:57,027 INFO FAN-C version: 0.9.14
Traceback (most recent call last):
  File "/nas/longleaf/home/alexisv7/.local/bin/fanc", line 127, in <module>
    Fanc()
  File "/nas/longleaf/home/alexisv7/.local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/fanc/commands/fanc_commands.py", line 4615, in aggregate
    with fanc.load(input_file, mode='r') as matrix:
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/fanc/tools/load.py", line 90, in load
    return gr_load(file_name, *args, **kwargs)
  File "/nas/longleaf/home/alexisv7/.local/lib/python3.8/site-packages/genomic_regions/regions.py", line 196, in load
    raise ValueError("File type not recognised ({}).".format(file_name))
ValueError: File type not recognised (HWT_K9me3_pel-merged_dm6_trim_q5_dupsRemoved_allFrags_peaks-with-width.bed).
```

What do I need to do to make my narrowPeak file compatible with fanc aggregate? Any help you can provide would be greatly appreciated!

Thanks so much for your help and for designing this software. I love fanc!

**Comment by kaukrise** [comment]
Hi, thanks a lot, it always makes me happy when there are a few nice words together with the issue!

Regarding the problem itself, is it possible that this is simply a mixup of arguments? I think currently you supply the regions first, then the matrix, but it should be the other way around:

```
usage: fanc aggregate [-h] [-m MATRIX_FILE] [-p PLOT_FILE] [--tads] [--tads-imakaev] [--loops] [--loop-strength LOOP_STRENGTH_FILE]
                      [--tad-strength TAD_STRENGTH_FILE] [-w WINDOW] [--pixels PIXELS] [-v REGION_VIEWPOINT] [-b BOUNDARY_MODE]
                      [-i INTERPOLATION] [-r RELATIVE] [-a ABSOLUTE] [-e] [-l] [--rescale] [--colormap COLORMAP] [--vmin VMIN] [--vmax VMAX]
                      [-tmp] [-C] [--keep-submatrices] [-s] [--lower-triangular-plot] [--labels LABELS] [--label-locations LABEL_LOCATIONS]
                      input [regions] [output]
```

Importantly, it is `input [regions] [output]`. So can you try the following command instead of your first attempt?

```
 fanc aggregate -m fanc-hwt-3LW-HiC-merge_2kb_k9me3-peaks-in-hwt.aggregateMatrix -p fanc-hwt-3LW-HiC-merge_2kb_k9me3-peaks-in-hwt.pdf -w 100000 ../fanc-hwt-3LW-HiC-merge/hic/binned/hwt-3LW-HiC-merge_2kb.hic ../../hp1a-cnr/k9me3_cnr/Peaks/HWT_K9me3_pel-merged_dm6_trim_q5_dupsRemoved_allFrags_peaks.narrowPeak test.agg
```

I have simply swapped the regions and the matrix file (and added an output file). It should accept the `.narrowPeak` file.

**Comment by 14stutzmanav** [comment]
Wow! Thanks so much for such a quick reply. I'm pleased (and somewhat embarrassed) to report that did the trick! I wonder how I missed that simple mistake. Anyway, thank you so much once again! This made my day!!

**Comment by kaukrise** [comment]
Excellent, thanks for reporting back so quickly!
