### ISSUE TITLE
tmp parameters

### ISSUE THREAD

**Issue by CocoMlle** [vaquerizaslab/fanc#74]
Hi! 
I have issue with the tmp files, i'm working on server (sge) and i followed the suggestions you gave and change the tmp dir: 

export TMPDIR=/work/gad/shared/tmp

Prologue begin
Starter begin : hauer027.u-bourgogne.fr(14531)
mer. sept.  8 13:30:35 CEST 2021
Version CentOS : 7.7
Starter(14531): PATH=/usr/ccub/sge/scripts:/tmp/6210652.1.batch:/work/gad/shared/bin/miniconda3/bin:/work/gad/shared/bin/miniconda3/bin:/work/gad/shared/bin/miniconda3/bin:/work/gad/shared/bin/miniconda3/bin:/work/gad/shared/bin/miniconda3/bin:/work/gad/shared/bin/miniconda2/bin:/work/gad/shared/bin/miniconda2/bin:/beegfs/data/work/gad/shared/bin/google-cloud-sdk/google-cloud-sdk/bin:/work/gad/shared/bin/miniconda2/bin:/work/gad/shared/bin/miniconda2/bin/mini:/user1/gad/ya0902du/.aspera/cli/bin:/work/gad/shared/bin/tcl/bin:/work/gad/shared/bin/miniconda2/bin:/work/gad/shared/bin/miniconda2/bin/bin:/work/gad/shared/bin/bin:/usr/local/intel/bin:/usr/ccub/sge/bin:/usr/ccub/sge/bin/lx-amd64:/bin:/usr/bin:/usr/sbin:/etc:/usr/ccub/bin:/usr/local/bin:/user1/gad/ya0902du/bin:/user1/gad/shared/bin:/work/gad/shared/bin:/work/gad/shared/bin/homer/bin:/work/c-shd/shared/software/bin:/work/gad/shared/diag/bin/BWA/bwa-0.7.6a:/work/gad/shared/bin/samtools/gcc-4.5.0:/user1/gad/shared/sources/samtools/samtools-0.1.18:/work/gad/shared/bin/freec:/work/gad/shared/bin/bedtools:/work/gad/shared/bin/bowtie2-2.3.2:/work/gad/shared/bin/tophat-2.1.1.Linux_x86_64:/work/gad/shared/bin/annovar:/soft/c7/cuda/9.1/bin/:/work/gad/shared/bin/barracuda/bin/:/work/gad/shared/bin/maven/apache-maven-3.6.1/bin/:/work/gad/shared/bin/git_lfs/:/soft/java/jdk1.8.0_162-x64/bin/:/soft/intel/2018u0/bin/:/soft/c7/R/3.6.2/gcc/9.1.0/bin/:/work/gad/shared/bin/gsutil/gsutil/:/soft/c7/go/1.14.2/go/bin/:/soft/singularity/2.4.0/bin/:/usr/ccub/sge-8.1.8/bin:/usr/ccub/sge-8.1.8/bin/lx-amd64:/work/gad/shared/bin/ruby/rvm/bin
Starter exec(14531) : '/usr/ccub/sge-8.1.8/ccub/spool/hauer027/job_scripts/6210652'
2021-09-08 13:31:05,029 INFO FAN-C version: 0.9.21
2021-09-08 13:31:05,201 INFO Output folder: output/
2021-09-08 13:31:05,201 INFO Input files: /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R1.fastq.gz, /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R2.fastq.gz
2021-09-08 13:31:05,201 INFO Input file types: fastq, fastq
2021-09-08 13:31:05,201 INFO Final basename: dijhic002_fanc (you can change this with the -n option!)
2021-09-08 13:31:05,201 INFO Creating output folders...
2021-09-08 13:31:11,352 INFO FAN-C version: 0.9.21
Traceback (most recent call last):
  File "/work/gad/shared/bin/miniconda3/bin/fanc", line 127, in <module>
    Fanc()
  File "/work/gad/shared/bin/miniconda3/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 394, in map
    input_file = create_temporary_copy(input_file, preserve_extension=True)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/genomic_regions/files.py", line 42, in create_temporary_copy
    shutil.copy2(src_file_name, tf.name)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device
Traceback (most recent call last):
  File "fanc", line 127, in <module>
    Fanc()
  File "fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 115, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/auto.py", line 1290, in auto
    runner.run()
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/auto.py", line 142, in run
    "Cancelling execution of all tasks.".format(task.id))
RuntimeError: Task a6b7d672-3869-4edd-9755-4ab0651c92d9 had non-zero exit status. Cancelling execution of all tasks.
Starter(14531): Return code=1
Starter end(14531)

but i checked the folder supposed to host the tmp files and definitly fanc didn't write anything inside, then i assume it didn't recognized my argument, do you have any idea? 
thanks for your help !
Marine

**Comment by kaukrise** [comment]
Hi there,

```
OSError: [Errno 28] No space left on device
```

Is it possible the `/tmp` partition is simply running out of space? Also, make sure the `TMPDIR` variable is set on the computing node, not the head node where you are submitting from.

**Comment by CocoMlle** [comment]
unfortunatly this is definitly not a problem of space.
is there a way to specify the output of the tmp without the env variable TMPDIR?

**Comment by kaukrise** [comment]
The `genomic_regions` package relies on `tempfile` to create temporary copies of files (or at least to get a filename): https://github.com/vaquerizaslab/genomic_regions/blob/da4a33c710f5552b6c8711d8e066f7d9cea46abf/genomic_regions/files.py#L41

Here is where `tempfile` looks in the operating system: https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir

As you can see, `TMPDIR` is the way to go. Can you please run you command with `-vvv` (`fanc -vvv ...`) to enable debug mode and post the full command and its output here?

**Comment by CocoMlle** [comment]
Prologue begin
Starter begin : bartok089.u-bourgogne.fr(115212)
mer. sept.  8 23:33:46 CEST 2021
Version CentOS : 7.7
Starter(115212): PATH=/usr/ccub/sge/scripts:/tmp/6211598.1.batch:/work/gad/shared/bin/miniconda3/bin:/beegfs/data/work/gad/shared/bin/google-cloud-sdk/google-cloud-sdk/bin:/work/gad/shared/bin/miniconda2
/bin:/work/gad/shared/bin/miniconda2/bin/mini:/user1/gad/ya0902du/.aspera/cli/bin:/work/gad/shared/bin/tcl/bin:/work/gad/shared/bin/miniconda2/bin:/work/gad/shared/bin/miniconda2/bin/bin:/work/gad/shared
/bin/bin:/usr/local/intel/bin:/usr/ccub/sge/bin:/usr/ccub/sge/bin/lx-amd64:/bin:/usr/bin:/usr/sbin:/etc:/usr/ccub/bin:/usr/local/bin:/user1/gad/ya0902du/bin:/user1/gad/shared/bin:/work/gad/shared/bin:/work/gad/shared/bin/homer/bin:/work/c-shd/shared/software/bin:/work/gad/shared/diag/bin/BWA/bwa-0.7.6a:/work/gad/shared/bin/samtools/gcc-4.5.0:/user1/gad/shared/sources/samtools/samtools-0.1.18:/work/gad/shared/bin/freec:/work/gad/shared/bin/bedtools:/work/gad/shared/bin/bowtie2-2.3.2:/work/gad/shared/bin/tophat-2.1.1.Linux_x86_64:/work/gad/shared/bin/annovar:/soft/c7/cuda/9.1/bin/:/work/gad/shared/bin/barracuda/bin/:/work/gad/shared/bin/maven/apache-maven-3.6.1/bin/:/work/gad/shared/bin/git_lfs/:/soft/java/jdk1.8.0_162-x64/bin/:/soft/intel/2018u0/bin/:/soft/c7/R/3.6.2/gcc/9.1.0/bin/:/work/gad/shared/bin/gsutil/gsutil/:/soft/c7/go/1.14.2/go/bin/:/soft/singularity/2.4.0/bin/:/usr/ccub/sge-8.1.8/bin:/usr/ccub/sge-8.1.8/bin/lx-amd64:/work/gad/shared/bin/ruby/rvm/bin
Starter exec(115212) : '/usr/ccub/sge-8.1.8/ccub/spool/bartok089/job_scripts/6211598'
2021-09-08 23:33:51,641 INFO FAN-C version: 0.9.21
2021-09-08 23:33:51,641 DEBUG Running 'fanc -vvv auto -g /work/gad/shared/analyse/HiC/analysis/juicer/restriction_sites/hg19_DpnII.txt -r DpnII -i /work/gad/shared/pipeline/hg19/index/hg19_essential -n dijhic002_fanc -t 10 --work-in-tmp /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R1.fastq.gz /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R2.fastq.gz output'
2021-09-08 23:33:51,769 INFO Output folder: output/
2021-09-08 23:33:51,769 INFO Input files: /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R1.fastq.gz, /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R2.fastq.gz
2021-09-08 23:33:51,769 INFO Input file types: fastq, fastq
2021-09-08 23:33:51,769 INFO Final basename: dijhic002_fanc (you can change this with the -n option!)
2021-09-08 23:33:51,769 INFO Creating output folders...
2021-09-08 23:33:51,788 DEBUG Running task b69af6b3-26d8-41a7-b890-12024a627acd
2021-09-08 23:33:56,613 INFO FAN-C version: 0.9.21
2021-09-08 23:33:56,614 DEBUG Running '/work/gad/shared/bin/miniconda3/bin/fanc -vvv map -m 25 -s 3 -t 10 -tmp --no-iterative /work/gad/shared/analyse/HiC/Marine/juicer/work/dijhic002/fastq/dijhic002_R1.fastq.gz /work/gad/shared/pipeline/hg19/index/hg19_essential output/sam/dijhic002_R1.bam'
2021-09-08 23:34:05,924 DEBUG Index path: /tmp/6211598.1.batch/tmps0dsn1wc/hg19_essential
2021-09-08 23:34:31,886 DEBUG Closing mapper
Traceback (most recent call last):
  File "/work/gad/shared/bin/miniconda3/bin/fanc", line 127, in <module>
    Fanc()
  File "/work/gad/shared/bin/miniconda3/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 394, in map
    input_file = create_temporary_copy(input_file, preserve_extension=True)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/genomic_regions/files.py", line 42, in create_temporary_copy
    shutil.copy2(src_file_name, tf.name)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device
Traceback (most recent call last):
  File "fanc", line 127, in <module>
    Fanc()
  File "fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 115, in auto
    return fanc.commands.auto.auto(argv, **kwargs)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/auto.py", line 1290, in auto
    runner.run()
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/fanc/commands/auto.py", line 142, in run
    "Cancelling execution of all tasks.".format(task.id))
RuntimeError: Task b69af6b3-26d8-41a7-b890-12024a627acd had non-zero exit status. Cancelling execution of all tasks.
Starter(115212): Return code=1
Starter end(115212)

**Comment by kaukrise** [comment]
Hi, it appears that `TMPDIR` is not set in the shell that `fanc auto` is run in. As far as I can see from your logs, `tempfile` still uses `/tmp/`, which is the default directory, suggesting it did not find your updated `TMPDIR`.

Can you please let me know when and in which shell exactly you are setting `TMPDIR`? Before submission or in the job submission script? What are the SGE submission parameters when you submit with `qsub`? Does it preserve the local environment?

**Comment by theshowmustgolangon** [comment]
@kaukrise I had same issue, OSError: [Errno 28] No space left on device, so I set -tmp and TMPDIR.
It look fanc get the setting but it shows error, https://github.com/vaquerizaslab/fanc/issues/78#issue-999785785 .
