### ISSUE TITLE
object has no attribute 'connection' 

### ISSUE THREAD

**Issue by gorliver** [vaquerizaslab/fanc#88]
Hi @kaukrise,
I have a bellow error message for `fanc pair -t 24`. 

```
2021-12-16 13:48:34,426 INFO FAN-C version: 0.9.21
2021-12-16 13:48:34,428 INFO Getting genome regions (fragments or bins)
2021-12-16 13:48:34,428 INFO Getting regions
2021-12-16 13:52:47,817 INFO Three arguments detected, assuming SAM/BAM input.
[E::idx_find_and_load] Could not retrieve index file for './fanc_output/sam/batch1_zhao-plant_S3HiC_R1_trimed.bam'
2021-12-16 13:52:47,819 INFO Using filters appropriate for BWA.
[E::idx_find_and_load] Could not retrieve index file for './fanc_output/sam/batch1_zhao-plant_S3HiC_R1_trimed.bam'
[E::idx_find_and_load] Could not retrieve index file for './fanc_output/sam/batch1_zhao-plant_S3HiC_R2_trimed.bam'
Exception ignored in: <generator object split_sam_pairs at 0x2b9525a9f740>
Traceback (most recent call last):
  File "/mnt/home/zhaohai3/.local/lib/python3.8/site-packages/fanc/pairs.py", line 173, in _split_sam_worker
    input_queue.put([pairs_file, chunk_size, unmappable])
RuntimeError: generator ignored GeneratorExit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/home/zhaohai3/.local/lib/python3.8/site-packages/fanc/pairs.py", line 173, in _split_sam_worker
    input_queue.put([pairs_file, chunk_size, unmappable])
  File "<string>", line 2, in put
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/home/zhaohai3/.local/lib/python3.8/site-packages/fanc/pairs.py", line 180, in _split_sam_worker
    monitor.set_generating_pairs(False)
  File "/mnt/home/zhaohai3/.local/lib/python3.8/site-packages/fanc/pairs.py", line 148, in set_generating_pairs
    with self.generating_pairs_lock:
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 1069, in __enter__
    return self._callmethod('acquire')
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 827, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/mnt/home/zhaohai3/.local/lib/python3.8/site-packages/fanc/pairs.py", line 188, in _load_paired_sam_worker
    monitor.set_worker_busy(worker_uuid)
  File "/mnt/home/zhaohai3/.local/lib/python3.8/site-packages/fanc/tools/general.py", line 514, in set_worker_busy
    with self.worker_lock:
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 1069, in __enter__
    return self._callmethod('acquire')
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 831, in _callmethod
    self._connect()
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/managers.py", line 818, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```
I thought something happened to the multiprocessing, so I set `-t 1` and it gives this message and generates a core.xxxx file:
```
2021-12-16 16:05:47,740 INFO FAN-C version: 0.9.21
2021-12-16 16:05:47,741 INFO Getting genome regions (fragments or bins)
2021-12-16 16:05:47,741 INFO Getting regions
/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
2021-12-16 16:10:16,892 INFO Three arguments detected, assuming SAM/BAM input.
[E::idx_find_and_load] Could not retrieve index file for './fanc_output/sam/batch1_zhao-plant_S3HiC_R1_trimed.bam'
2021-12-16 16:10:16,914 INFO Using filters appropriate for BWA.
[E::idx_find_and_load] Could not retrieve index file for './fanc_output/sam/batch1_zhao-plant_S3HiC_R1_trimed.bam'
[E::idx_find_and_load] Could not retrieve index file for './fanc_output/sam/batch1_zhao-plant_S3HiC_R2_trimed.bam'
/mnt/home/zhaohai3/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Bus error
```
Could it be anything wrong?
Thank you!

**Comment by kaukrise** [comment]
Hey, I'm sorry, I have never encountered this issue. From this [question](https://stackoverflow.com/questions/64515797/there-appear-to-be-6-leaked-semaphore-objects-to-clean-up-at-shutdown-warnings-w) it seems your system might not be able to handle to workload? The `Bus error` also indicates [memory issue](https://stackoverflow.com/a/37817521)
