### ISSUE TITLE
fanc aggregate error, a wrong bedpe file ?

### ISSUE THREAD

**Issue by AIBio** [vaquerizaslab/fanc#90]
Hi,

I want to get loop aggregate plots using 'fanc aggregate'. But I got an unsolved problem. Here is the running command and error message: 

`fanc aggregate -p test.png --loops ${cool_matrix} test.bedpe test.agg`

> 2021-12-26 17:42:38,146 INFO Detected BEDPE. Running pairwise region extraction
Traceback (most recent call last):
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/fanc/compatibility/cooler.py", line 355, in _region_subset
    df = self.bins().fetch(query)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/core.py", line 539, in fetch
    lo, hi = self._fetch(*args, **kwargs)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/api.py", line 264, in _fetch
    grp, self._chromids, parse_region(region, self._chromsizes)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 160, in parse_region
    chrom, start, end = parse_region_string(reg)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 136, in parse_region_string
    start, end = _expect(_tokenize(parts[1]))
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 114, in _expect
    start = parse_humanized(token)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 60, in parse_humanized
    return int(value)
ValueError: invalid literal for int() with base 10: '100019999.0'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/bin/fanc", line 127, in <module>
    Fanc()
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/fanc/commands/fanc_commands.py", line 4672, in aggregate
    region_viewpoint=region_viewpoint)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/fanc/architecture/aggregate.py", line 420, in from_center_pairs
    **kwargs):
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/fanc/architecture/aggregate.py", line 736, in _loop_matrix_iterator
    r1 = list(hic.regions(a1))[0].copy()
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/fanc/compatibility/cooler.py", line 361, in _region_subset
    df = self.bins().fetch(query)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/core.py", line 539, in fetch
    lo, hi = self._fetch(*args, **kwargs)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/api.py", line 264, in _fetch
    grp, self._chromids, parse_region(region, self._chromsizes)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 160, in parse_region
    chrom, start, end = parse_region_string(reg)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 136, in parse_region_string
    start, end = _expect(_tokenize(parts[1]))
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 114, in _expect
    start = parse_humanized(token)
  File "/home/cmq/software/anaconda3/envs/dna.p3r4/lib/python3.7/site-packages/cooler/util.py", line 60, in parse_humanized
    return int(value)
> ValueError: invalid literal for int() with base 10: '100019999.0'

I think the problem may come from wrong loop region file. My matrix file was generated with hicexplorer. My bedpe file contain six columns that record the two sets of regions.

> chr10	100040000	100080000	chr10	100280000	100320000
> chr10	100080000	100120000	chr10	100240000	100280000

Could you give me some helps to fix it?

Thank you~

Hanwen

**Comment by kaukrise** [comment]
Hey, I'm currently on holiday, so I don't have time to reply in depth.

This looks like a compatibility issue with Cooler files - I'll look into this once I am back at work. In the meantime you could try to convert to FAN-C format using `fanc hic --deepcopy` first

**Comment by AIBio** [comment]
> 
Thank you for your reply,

I downloaded the example data your group provided. Two columns are missed in my bedpe file. But it didn't work for my cool matrix file. Your suggestion may be useful for me. I try to convert to FAN-C format using fanc hic --deepcopy first.

Happy holidays 

Hanwen
