### ISSUE TITLE
fanc hic error

### ISSUE THREAD

**Issue by SOlsthoorn** [vaquerizaslab/fanc#93]
Hi,

When I try this: 

`fanc hic --chromosomes 10 11 -b 100k -a -n -s hic/statistics hic/SRR620257_17_fragmentlevel.hic hic/SRR620257_17_100kb3.hic`

I get the following error:

2022-02-01 12:12:36,999 INFO FAN-C version: 0.9.21
2022-02-01 12:12:37,034 INFO Binning Hic file (100000)
2022-02-01 12:12:37,034 INFO Constructing binned genome...
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 127, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.6/dist-packages/fanc/commands/fanc_commands.py", line 1487, in hic
    threads=threads, chromosomes=limit_chromosomes)
  File "/usr/local/lib/python3.6/dist-packages/fanc/hic.py", line 340, in bin
    chromosome_list.append(Chromosome(name=chromosome, length=self.chromosome_lengths[chromosome]))
KeyError: '10'
Closing remaining open files:hic/SRR620257_17_fragmentlevel.hic...done

Is there anything I am doing wrong?

Thank you

Simone

**Comment by kaukrise** [comment]
Hi, this indicates that `10` is not a valid chromosome identifier. Have you tried `--chromosomes chr10 chr11`?

**Comment by SOlsthoorn** [comment]
@kaukrise thank you! This seems to be working 👍
