### ISSUE TITLE
 raise ValueError(msg) ValueError: Trying to re-register the builtin cmap 'viridis'.

### ISSUE THREAD

**Issue by robeach78** [vaquerizaslab/fanc#94]
Trying to run basic command in conda env:

chr18:6mb-10mb -p triangular adj_hESCs_HiC_contact_map.hic

but getting this error:

(fanc_env) marcrobert@marcrobert-MBP examples % fancplot chr18:6mb-10mb -p triangular adj_hESCs_HiC_contact_map.hic 
Traceback (most recent call last):
  File "/Users/marcrobert/opt/miniconda3/envs/fanc_env/bin/fancplot", line 230, in <module>
    FancPlot()
  File "/Users/rmarcrobert/opt/miniconda3/envs/fanc_env/bin/fancplot", line 64, in __init__
    import fanc.plotting as kplot
  File "/Users/marcrobert/opt/miniconda3/envs/fanc_env/lib/python3.7/site-packages/fanc/plotting/__init__.py", line 218, in <module>
    plt.register_cmap(name='viridis', cmap=viridis)
  File "/Users/marcrobert/opt/miniconda3/envs/fanc_env/lib/python3.7/site-packages/matplotlib/cm.py", line 245, in register_cmap
    raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'viridis'.

Any advise?

thanks a lot

**Comment by kaukrise** [comment]
Hi, the conda version of FAN-C is outdated. Please install the latest version using `pip` or install from source. Thanks! Kai
