### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by yancychy** [vaquerizaslab/fanc#98]
Hi, when I run the fanc aggregate. It produces errors with fixed window size.  
Is it possible to fix it? Thanks.

fanc aggregate $sc $lp $ag -p $pg -m $tg --loop-strength $st -l -e -w 500000 --colormap "coolwarm"

2022-02-24 20:04:37,130 INFO FAN-C version: 0.9.21
2022-02-24 20:04:37,344 INFO Detected BEDPE. Running pairwise region extraction
Traceback (most recent call last):
  File "/usr/local/bin/fanc", line 127, in <module>
    Fanc()
  File "/usr/local/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/usr/local/lib/python3.8/dist-packages/fanc/commands/fanc_commands.py", line 4665, in aggregate
    aggregate_matrix = AggregateMatrix.from_center_pairs(matrix, region_pairs,
  File "/usr/local/lib/python3.8/dist-packages/fanc/architecture/aggregate.py", line 416, in from_center_pairs
    counter_matrix = np.zeros(shape)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by kaukrise** [comment]
Hi, this is strange - `shape`, which seems to be causing the issue, is just `(pixels, pixels)`, and `pixel` is an integer. Can you please install the below beta version and send me the output again? I've added some debug info.

[fanc-0.9.23b0.tar.gz](https://github.com/vaquerizaslab/fanc/files/8139019/fanc-0.9.23b0.tar.gz)

**Comment by yancychy** [comment]
Thanks. The following is the new errors: 

2022-02-25 12:57:27,138 INFO FAN-C version: 0.9.23b0
Traceback (most recent call last):
  File "/data/cheny48/conda/bin/fanc", line 4, in <module>
    __import__('pkg_resources').run_script('fanc==0.9.23b0', 'fanc')
  File "/data/cheny48/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/cheny48/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/gsfs12/users/cheny48/conda/lib/python3.7/site-packages/fanc-0.9.23b0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fanc", line 127, in <module>
    Fanc()
  File "/gpfs/gsfs12/users/cheny48/conda/lib/python3.7/site-packages/fanc-0.9.23b0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/gpfs/gsfs12/users/cheny48/conda/lib/python3.7/site-packages/fanc-0.9.23b0-py3.7-linux-x86_64.egg/fanc/commands/fanc_commands.py", line 4816, in aggregate
    np.savetxt(matrix_file, aggregate_matrix.matrix())
AttributeError: 'NoneType' object has no attribute 'matrix'
Closing remaining open files:juicerRes/mock1_5kb_CP190kdloop.agg...done
